#!/usr/bin/env python3
"""Stdlib-ONLY accel-ppp config generator — the single source of truth.

This module deliberately imports **nothing but the Python standard library**:
no Flask, no `app`, no DB. That lets the host installer
(``install-accel-selfsigned.sh``) generate ``/etc/accel-ppp.conf`` with plain
system ``python3`` even when the panel runs inside Docker (where Flask lives but
the host interpreter has no dependencies). The app-side wrapper
(``app/radius/services/accel_config.py``) imports the pure functions from here,
so there is exactly one copy of the template and the output is byte-identical no
matter who renders it.

Why it exists: the live VPS config was first built with manual ``sed``/append
edits that produced **duplicated** ``[radius]`` / ``[auth]`` /
``[client-ip-range]`` sections and an over-restrictive TLS policy
(``ssl-protocol=tlsv1.2`` + ``ssl-ciphers=AES256-SHA``) → MikroTik
``ssl: no common version (6)``. This generator emits each section exactly once
and pins **no** TLS protocol/cipher, so OpenSSL negotiates
``ECDHE-RSA-AES256-GCM-SHA384`` freely.

Runtime values come from (highest precedence first): explicit CLI overrides →
``--env-file`` → process environment → built-in defaults. NEVER from importing
the app.

CLI:
    accel_conf_gen.py config [--out FILE]        # full /etc/accel-ppp.conf
    accel_conf_gen.py print <key>                # one resolved value
    accel_conf_gen.py openssl-cmd                # shell-quoted openssl argv
  common options: --env-file PATH and per-key overrides (--pool, --sstp-port …)
"""
from __future__ import annotations

import argparse
import ipaddress
import os
import shlex
import sys
from dataclasses import dataclass

# ─── env keys + defaults (MUST match app/radius/core/env_settings + rmt) ──────
ENV_POOL = "HOBERADIUS_MGMT_TUNNEL_POOL"
ENV_SERVER_IP = "HOBERADIUS_MGMT_TUNNEL_SERVER_IP"
ENV_SSTP_PORT = "HOBERADIUS_ACCEL_SSTP_PORT"
ENV_RADIUS_SERVER = "HOBERADIUS_ACCEL_RADIUS_SERVER"
ENV_RADIUS_SECRET = "HOBERADIUS_ACCEL_RADIUS_SECRET"
ENV_SSL_PEMFILE = "HOBERADIUS_ACCEL_SSL_PEMFILE"
ENV_SSL_KEYFILE = "HOBERADIUS_ACCEL_SSL_KEYFILE"

DEFAULT_POOL = "10.50.0.0/24"
DEFAULT_SSTP_PORT = 443
DEFAULT_RADIUS_SERVER = "127.0.0.1"
DEFAULT_RADIUS_SECRET = "accel-local-secret"
DEFAULT_SSL_PEMFILE = "/etc/accel-ppp/accel-selfsigned.pem"
DEFAULT_SSL_KEYFILE = "/etc/accel-ppp/accel-selfsigned.key"
DEFAULT_DAE_PORT = 3799


@dataclass(frozen=True)
class AccelParams:
    """Everything :func:`generate_accel_conf` needs. Validated so a bad pool/IP
    fails before we ever write a broken config."""

    pool: ipaddress.IPv4Network
    gateway_ip: ipaddress.IPv4Address      # server's IP inside the pool
    sstp_port: int
    radius_server: str
    radius_secret: str
    ssl_pemfile: str                       # certificate (PEM)
    ssl_keyfile: str = DEFAULT_SSL_KEYFILE  # private key (separate file)
    dae_port: int = DEFAULT_DAE_PORT

    @property
    def pool_range(self) -> str:
        """accel ``[ip-pool]`` range. We emit the explicit CIDR form which is
        unambiguous and survives any pool size; accel hands out the gateway as
        gw-ip-address and leases the rest."""
        hosts = list(self.pool.hosts())
        usable = [h for h in hosts if h != self.gateway_ip]
        if not usable:
            raise ValueError("مجمّع الإدارة صغير جدًّا — لا عناوين بعد البوّابة")
        return str(self.pool)


def _scrub(value: str) -> str:
    """Strip characters that would break the flat ini-ish accel config
    (newlines / NULs) so a pasted secret/path can't inject a section."""
    return "".join(ch for ch in str(value or "") if ch not in "\r\n\x00").strip()


# ─── the generator (single source — app imports this) ─────────────────────────

def generate_accel_conf(params: AccelParams) -> str:
    """Render a complete, clean ``/etc/accel-ppp.conf``.

    Every section appears EXACTLY once. Output is stable for a given ``params``
    (no timestamps / randomness), so re-running the installer is a no-op when
    settings are unchanged.
    """
    if params.gateway_ip not in params.pool:
        raise ValueError("البوّابة خارج المجمّع")

    secret = _scrub(params.radius_secret)
    server = _scrub(params.radius_server)
    pem = _scrub(params.ssl_pemfile)
    key = _scrub(params.ssl_keyfile)
    gw = str(params.gateway_ip)
    pool_cidr = params.pool_range
    sstp_port = int(params.sstp_port)
    dae_port = int(params.dae_port)

    return f"""\
# ─────────────────────────────────────────────────────────────────────────
# /etc/accel-ppp.conf — GENERATED by HobeRadius (deploy/accel-ppp/
# accel_conf_gen.py — stdlib-only). DO NOT hand-edit: re-running the installer
# overwrites this file from settings. Change values in the panel / env instead.
#
# v6 router MANAGEMENT tunnel: SSTP :{sstp_port} (default) / PPTP :1723,
# authenticating rtr-* accounts against the local FreeRADIUS; CoA/DAE :{dae_port}.
# Each section appears exactly once — no duplicates.
# ─────────────────────────────────────────────────────────────────────────

[modules]
log_file
# transports
sstp
pptp
# auth methods (MSCHAP-v2 is what MikroTik SSTP/PPTP negotiate)
auth_mschap_v2
auth_mschap_v1
auth_chap_md5
auth_pap
# backend + addressing + shaping
radius
ippool
shaper

[core]
thread-count=4

[log]
log-file=/var/log/accel-ppp/accel-ppp.log
log-emerg=/var/log/accel-ppp/emerg.log
log-fail-file=/var/log/accel-ppp/auth-fail.log
copy=1
level=3

[ppp]
verbose=1
min-mtu=1280
mtu=1400
mru=1400
# accept any of the negotiated MSCHAP variants; PAP last-resort.
ipv4=require
ipv6=deny
lcp-echo-interval=30
lcp-echo-failure=3
unit-cache=1

[auth]
# Order MikroTik prefers; mschap-v2 first.

[sstp]
# SSTP is TLS already. We bind the TLS listener with a self-signed cert and —
# critically — do NOT pin ssl-protocol / ssl-ciphers. Letting OpenSSL negotiate
# is what allows MikroTik's ECDHE-RSA-AES256-GCM-SHA384 to be selected; the old
# pinned tlsv1.2 + AES256-SHA caused "ssl: no common version (6)".
#
# ssl-pemfile = CERTIFICATE, ssl-keyfile = PRIVATE KEY — emitted as SEPARATE
# files. A single combined pemfile (and minting with `-keyout f -out f`) is
# unreliable: the cert write truncates the key, leaving accel with a cert but
# NO usable private key → the TLS handshake fails and `accel-pppd -t` warns.
verbose=1
accept=ssl
ssl-pemfile={pem}
ssl-keyfile={key}
port={sstp_port}

[pptp]
verbose=1

[client-ip-range]
0.0.0.0/0

[ip-pool]
gw-ip-address={gw}
{pool_cidr}

[radius]
verbose=1
nas-identifier=accel-mgmt
nas-ip-address={gw}
gw-ip-address={gw}
server={server},{secret},auth-port=1812,acct-port=1813,req-limit=0,fail-time=0
dae-server=127.0.0.1:{dae_port},{secret}
acct-timeout=0
timeout=10
max-try=3

[shaper]
verbose=1

[cli]
tcp=127.0.0.1:2001
"""


def openssl_selfsigned_cmd(certfile: str, keyfile=None, *, days: int = 3650,
                           cn: str = "hoberadius-accel") -> list:
    """The exact openssl invocation the installer uses to mint the self-signed
    SSTP cert (argv list — no shell interpolation).

    Writes the private key and certificate to SEPARATE files (``-keyout`` →
    keyfile, ``-out`` → certfile). Never the same path for both: that overwrites
    the key. ``keyfile`` defaults to ``certfile`` with a ``.key`` extension."""
    if not keyfile:
        keyfile = _default_keyfile_for(certfile)
    return [
        "openssl", "req", "-x509", "-nodes", "-newkey", "rsa:2048",
        "-days", str(int(days)), "-subj", "/CN=" + cn,
        "-keyout", keyfile, "-out", certfile,
    ]


def _default_keyfile_for(certfile: str) -> str:
    """Sibling ``.key`` path next to the certificate (deterministic)."""
    base, ext = os.path.splitext(certfile)
    return (base + ".key") if ext else (certfile + ".key")


# ─── parameter resolution (env-file / env / defaults / overrides) ─────────────

def load_env_file(path: str) -> dict:
    """Parse a ``KEY=VALUE`` env file (``.env`` style). Ignores blanks/comments
    and a leading ``export``. Quotes around the value are stripped. Returns only
    the accel-relevant keys."""
    wanted = {ENV_POOL, ENV_SERVER_IP, ENV_SSTP_PORT, ENV_RADIUS_SERVER,
              ENV_RADIUS_SECRET, ENV_SSL_PEMFILE, ENV_SSL_KEYFILE}
    out: dict = {}
    try:
        with open(path, encoding="utf-8") as fh:
            for raw in fh:
                line = raw.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                if line.lower().startswith("export "):
                    line = line[7:].lstrip()
                key, _, val = line.partition("=")
                key = key.strip()
                if key not in wanted:
                    continue
                val = val.strip()
                if len(val) >= 2 and val[0] == val[-1] and val[0] in "\"'":
                    val = val[1:-1]
                out[key] = val
    except OSError:
        pass
    return out


def _first(*vals):
    for v in vals:
        if v is not None and str(v).strip() != "":
            return str(v).strip()
    return None


def resolve_params(env=None, overrides=None) -> AccelParams:
    """Resolve effective params. Precedence (high→low):
    ``overrides`` (CLI) → ``env`` mapping → built-in defaults.

    ``overrides`` keys: pool, gateway, sstp_port, radius_server, radius_secret,
    ssl_pemfile, ssl_keyfile, dae_port. ``env`` is any mapping of the
    HOBERADIUS_* keys (e.g. ``os.environ`` merged with an --env-file)."""
    env = env or {}
    overrides = overrides or {}

    pool_str = _first(overrides.get("pool"), env.get(ENV_POOL), DEFAULT_POOL)
    pool = ipaddress.ip_network(pool_str, strict=False)
    if not isinstance(pool, ipaddress.IPv4Network):
        raise ValueError("مجمّع الإدارة يجب أن يكون IPv4: " + repr(pool_str))

    gw_str = _first(overrides.get("gateway"), env.get(ENV_SERVER_IP))
    gateway = ipaddress.ip_address(gw_str) if gw_str else next(pool.hosts())
    if gateway not in pool:
        raise ValueError("البوّابة %s خارج المجمّع %s" % (gateway, pool))

    port_str = _first(overrides.get("sstp_port"), env.get(ENV_SSTP_PORT),
                      str(DEFAULT_SSTP_PORT))
    try:
        sstp_port = int(port_str)
    except (TypeError, ValueError):
        sstp_port = DEFAULT_SSTP_PORT

    ssl_pemfile = _first(overrides.get("ssl_pemfile"),
                         env.get(ENV_SSL_PEMFILE), DEFAULT_SSL_PEMFILE)
    # Key defaults to a sibling .key of the cert (so a custom pemfile keeps its
    # key alongside) unless explicitly overridden.
    ssl_keyfile = _first(overrides.get("ssl_keyfile"), env.get(ENV_SSL_KEYFILE),
                         _default_keyfile_for(ssl_pemfile))

    return AccelParams(
        pool=pool,
        gateway_ip=gateway,
        sstp_port=sstp_port,
        radius_server=_first(overrides.get("radius_server"),
                             env.get(ENV_RADIUS_SERVER), DEFAULT_RADIUS_SERVER),
        radius_secret=_first(overrides.get("radius_secret"),
                             env.get(ENV_RADIUS_SECRET), DEFAULT_RADIUS_SECRET),
        ssl_pemfile=ssl_pemfile,
        ssl_keyfile=ssl_keyfile,
        dae_port=int(_first(overrides.get("dae_port"), str(DEFAULT_DAE_PORT))),
    )


# ─── CLI ──────────────────────────────────────────────────────────────────────

_PRINT_KEYS = {
    "sstp_port": lambda p: str(p.sstp_port),
    "ssl_pemfile": lambda p: p.ssl_pemfile,
    "ssl_keyfile": lambda p: p.ssl_keyfile,
    "radius_secret": lambda p: p.radius_secret,
    "radius_server": lambda p: p.radius_server,
    "gateway": lambda p: str(p.gateway_ip),
    "pool": lambda p: str(p.pool),
    "dae_port": lambda p: str(p.dae_port),
}


def _build_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(
        prog="accel_conf_gen.py",
        description="Stdlib-only accel-ppp config generator (no Flask/app).")
    ap.add_argument("--env-file", help="KEY=VALUE file to load before env.")
    for opt in ("pool", "gateway", "sstp-port", "radius-server",
                "radius-secret", "ssl-pemfile", "ssl-keyfile", "dae-port"):
        ap.add_argument("--" + opt)
    sub = ap.add_subparsers(dest="cmd", required=True)
    c = sub.add_parser("config", help="print the full /etc/accel-ppp.conf")
    c.add_argument("--out", help="write to FILE instead of stdout")
    p = sub.add_parser("print", help="print one resolved value")
    p.add_argument("key", choices=sorted(_PRINT_KEYS))
    sub.add_parser("openssl-cmd", help="print shell-quoted openssl argv")
    return ap


def _overrides_from_args(args) -> dict:
    return {
        "pool": args.pool, "gateway": args.gateway,
        "sstp_port": getattr(args, "sstp_port", None),
        "radius_server": getattr(args, "radius_server", None),
        "radius_secret": getattr(args, "radius_secret", None),
        "ssl_pemfile": getattr(args, "ssl_pemfile", None),
        "ssl_keyfile": getattr(args, "ssl_keyfile", None),
        "dae_port": getattr(args, "dae_port", None),
    }


def main(argv=None) -> int:
    args = _build_parser().parse_args(argv)
    env = dict(os.environ)
    if args.env_file:
        # env-file values fill in only what the process env doesn't already set.
        for k, v in load_env_file(args.env_file).items():
            env.setdefault(k, v)
    try:
        params = resolve_params(env=env, overrides=_overrides_from_args(args))
    except ValueError as exc:
        sys.stderr.write("accel_conf_gen: %s\n" % exc)
        return 2

    if args.cmd == "config":
        text = generate_accel_conf(params)
        if getattr(args, "out", None):
            with open(args.out, "w", encoding="utf-8", newline="\n") as fh:
                fh.write(text)
        else:
            # Force UTF-8 regardless of the platform's stdout encoding (the
            # template has Arabic comments; Windows cp1256 / POSIX C locale
            # would otherwise choke). Linux VPS stdout is already UTF-8.
            sys.stdout.buffer.write(text.encode("utf-8"))
        return 0
    if args.cmd == "print":
        sys.stdout.write(_PRINT_KEYS[args.key](params) + "\n")
        return 0
    if args.cmd == "openssl-cmd":
        cmd = openssl_selfsigned_cmd(params.ssl_pemfile, params.ssl_keyfile)
        sys.stdout.write(" ".join(shlex.quote(a) for a in cmd) + "\n")
        return 0
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
