#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# install-accel-selfsigned.sh — deterministic, idempotent accel-ppp setup for
# the v6 router MANAGEMENT tunnel (SSTP :443 / PPTP :1723).
#
# Replaces the old manual sed/append workflow that produced duplicated
# [radius]/[auth]/[client-ip-range] sections and an over-restrictive TLS policy
# (ssl-protocol=tlsv1.2 + ssl-ciphers=AES256-SHA → MikroTik "ssl: no common
# version (6)").
#
# The config is generated by a STDLIB-ONLY script
# (deploy/accel-ppp/accel_conf_gen.py) — it imports nothing but the Python
# standard library, so this runs with plain host `python3` even when the panel
# runs inside Docker (Flask lives in the container; accel-ppp binds host :443).
# No venv, no `import app`, no Flask required on the host.
#
# Parameter sources (highest precedence first): explicit env on this shell →
# --env-file → an optional docker-exec export of the panel's effective settings
# → built-in defaults. We:
#   1. (optional) pull the panel's effective params via `docker exec` so values
#      set ONLY in the UI propagate without the host needing Flask,
#   2. detect a :443 conflict (nginx/docker) and refuse to clobber it,
#   3. ensure /dev/ppp + PPP kernel modules,
#   4. mint a self-signed SSTP cert if missing,
#   5. back up any existing /etc/accel-ppp.conf (timestamped),
#   6. write the generated config + assert no duplicate sections / no TLS pin,
#   7. (re)start accel-ppp,
#   8. run startup health checks (listener, TLS handshake, radtest mschap).
#
# Safe to run repeatedly. Requires root. Env overrides (all optional):
#   HOBERADIUS_REPO            path to the repo (default: autodetect from script)
#   HOBERADIUS_ACCEL_CONF      target conf path (default: /etc/accel-ppp.conf)
#   HOBERADIUS_ENV_FILE        explicit KEY=VALUE file to feed the generator
#   HOBERADIUS_PANEL_CONTAINER panel container name/id for the param export
#                              (default: autodetect a 'hoberadius' container)
#   HOBERADIUS_NO_DOCKER_EXPORT=1   skip the docker-exec param export
#   ACCEL_TEST_USER / ACCEL_TEST_PASS   radtest mschap probe (optional)
#   PYTHON                     host python3 to use (default: python3)
# Per-key overrides also accepted by the generator and passed through if set:
#   HOBERADIUS_MGMT_TUNNEL_POOL / _SERVER_IP, HOBERADIUS_ACCEL_SSTP_PORT,
#   HOBERADIUS_ACCEL_RADIUS_SERVER / _SECRET, HOBERADIUS_ACCEL_SSL_PEMFILE
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

log()  { printf '\033[1;34m[accel]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[accel WARN]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m[accel FAIL]\033[0m %s\n' "$*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "يجب تشغيله بصلاحيات root."

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="${HOBERADIUS_REPO:-$(cd "$SCRIPT_DIR/../.." && pwd)}"
CONF="${HOBERADIUS_ACCEL_CONF:-/etc/accel-ppp.conf}"
PYBIN="${PYTHON:-python3}"
GEN="$SCRIPT_DIR/accel_conf_gen.py"

[ -f "$GEN" ] || die "مولّد الإعداد غير موجود: $GEN"
command -v docker >/dev/null 2>&1 && DOCKER_OK=1 || DOCKER_OK=0

# Panel container (Docker deployment): used for the optional param export and
# as the no-host-python fallback interpreter. Name is `hoberadius` by default.
PANEL_CID="${HOBERADIUS_PANEL_CONTAINER:-}"
if [ -z "$PANEL_CID" ] && [ "$DOCKER_OK" = 1 ]; then
    PANEL_CID="$(docker ps --filter "name=hoberadius" -q 2>/dev/null | head -n1)"
fi

# Interpreter strategy: PREFER host python3 + the stdlib generator (zero deps,
# no Flask). Only if host python3 is missing do we fall back to running the
# panel container's app (Flask lives there) — same output, reads UI-set DB
# params directly. The stdlib CLI never needs an app context.
HOSTPY=""
if command -v "$PYBIN" >/dev/null 2>&1; then HOSTPY="$PYBIN"; fi
if [ -z "$HOSTPY" ]; then
    { [ "$DOCKER_OK" = 1 ] && [ -n "$PANEL_CID" ]; } \
        || die "لا $PYBIN على المضيف ولا حاوية لوحة (hoberadius) متاحة لتشغيل المولّد."
    warn "لا python3 على المضيف — أشغّل المولّد عبر حاوية اللوحة ${PANEL_CID}."
fi

TMPDIR_RUN="$(mktemp -d)"
trap 'rm -rf "$TMPDIR_RUN"' EXIT

# ── 0a) env-file + optional UI-param export (host-python path only; the ───────
#         container fallback reads the DB directly, so it needs neither).
ENV_FILE=""
if [ -n "$HOSTPY" ]; then
    for cand in "${HOBERADIUS_ENV_FILE:-}" "$REPO/.env" /opt/hoberadius/.env \
                /etc/hoberadius/.env /etc/hoberadius.env; do
        if [ -n "$cand" ] && [ -f "$cand" ]; then ENV_FILE="$cand"; break; fi
    done
    # Values set ONLY in the panel UI live in the (encrypted) DB, which host
    # python3 cannot read. If a panel container is reachable, ask it (Flask is
    # available there) to print KEY=VALUE lines and feed THAT to the stdlib
    # generator. Never blocks: any failure falls back to env-file/env/defaults.
    if [ "${HOBERADIUS_NO_DOCKER_EXPORT:-0}" != "1" ] && [ "$DOCKER_OK" = 1 ] && [ -n "$PANEL_CID" ]; then
        EXPORTED="$TMPDIR_RUN/panel.env"
        if docker exec "$PANEL_CID" python3 -c \
            "from app.radius.services import accel_config as ac; print(chr(10).join(ac.export_env_lines()))" \
            > "$EXPORTED" 2>/dev/null && [ -s "$EXPORTED" ]; then
            ENV_FILE="$EXPORTED"
            log "صُدّرت إعدادات اللوحة الفعليّة من الحاوية $PANEL_CID."
        else
            warn "تعذّر تصدير إعدادات اللوحة من الحاوية — أعتمد env-file/env/الافتراضات."
        fi
    fi
fi

ENV_ARG=()
[ -n "$ENV_FILE" ] && { ENV_ARG=(--env-file "$ENV_FILE"); log "ملف الإعدادات: $ENV_FILE"; }

# gen <subcommand...> — host stdlib generator if python3 exists, else the panel
# container's app (path-independent; reads UI-set DB params).
gen() {
    if [ -n "$HOSTPY" ]; then
        "$HOSTPY" "$GEN" "${ENV_ARG[@]}" "$@"
    else
        _gen_via_container "$@"
    fi
}
_gen_via_container() {
    case "$1" in
        config)
            docker exec -i "$PANEL_CID" python3 -c \
"from app.radius.services import accel_config as ac,sys; sys.stdout.write(ac.generate_accel_conf(ac.params_from_settings()))" ;;
        print)
            docker exec -i "$PANEL_CID" python3 -c \
"from app.radius.services import accel_config as ac; print(getattr(ac.params_from_settings(), '$2'))" ;;
        openssl-cmd)
            docker exec -i "$PANEL_CID" python3 -c \
"from app.radius.services import accel_config as ac,shlex; p=ac.params_from_settings(); print(' '.join(shlex.quote(a) for a in ac.openssl_selfsigned_cmd(p.ssl_pemfile, p.ssl_keyfile)))" ;;
        *) die "أمر مولّد غير معروف: $1" ;;
    esac
}

# ── 1) Resolve params from the stdlib generator (no Flask) ────────────────────
# Single source: gateway IP + RADIUS secret here drive BOTH the accel [radius]
# config AND the lo address + FreeRADIUS client file below, so they can never
# drift apart.
SSTP_PORT="$(gen print sstp_port)"      || die "تعذّر حساب منفذ SSTP."
PEMFILE="$(gen print ssl_pemfile)"      || die "تعذّر حساب مسار الشهادة."
KEYFILE="$(gen print ssl_keyfile)"      || die "تعذّر حساب مسار المفتاح."
GATEWAY="$(gen print gateway)"          || die "تعذّر حساب عنوان البوّابة."
RAD_SECRET="$(gen print radius_secret)" || die "تعذّر حساب سرّ RADIUS."
log "منفذ SSTP=${SSTP_PORT}  شهادة=${PEMFILE}  مفتاح=${KEYFILE}  بوّابة=${GATEWAY}"

# ── 2) Port conflict detection — accel-pppd is OURS, not a conflict ───────────
# A normal re-run finds :443 held by accel-pppd (our own SSTP server, which we
# restart below). That must NOT abort. We only refuse when a FOREIGN process
# (nginx, docker-proxy, apache, …) holds the port.
if command -v ss >/dev/null 2>&1; then
    HOLDERS="$(ss -ltnpH "sport = :${SSTP_PORT}" 2>/dev/null \
        | grep -oE 'users:\(\("[^"]+"' | grep -oE '"[^"]+"' | tr -d '"' | sort -u)"
    FOREIGN=""
    for h in $HOLDERS; do
        case "$h" in
            accel-pppd|accel-ppp) : ;;            # our SSTP server — fine
            *) FOREIGN="$FOREIGN $h" ;;
        esac
    done
    FOREIGN="$(printf '%s' "$FOREIGN" | tr -s ' ' | sed -e 's/^ //' -e 's/ $//')"
    if [ -n "$FOREIGN" ]; then
        die "منفذ ${SSTP_PORT} مشغول بعملية أجنبية: ${FOREIGN}. أوقفها (nginx/docker-proxy/apache على هذا المنفذ) ثم أعد التشغيل — مستمع SSTP يحتاج المنفذ. ملاحظة: إن كانت حاوية nginx تنشر :443 في docker-compose، أزِل خريطة \"443:443\" منها لتحرير المنفذ لـaccel على المضيف."
    fi
    if [ -n "$HOLDERS" ]; then
        log "منفذ ${SSTP_PORT} يملكه accel-pppd (خادمنا) — سيُعاد تشغيله، ليس تعارضًا."
    else
        log "منفذ ${SSTP_PORT} متاح."
    fi
else
    log "ss غير متوفّر — تخطّي فحص تعارض المنفذ."
fi

# ── 3) /dev/ppp + kernel modules ─────────────────────────────────────────────
for mod in ppp_generic ppp_async ppp_synctty ppp_mppe; do
    modprobe "$mod" 2>/dev/null || warn "تعذّر تحميل وحدة $mod (قد تكون مدمجة في النواة)."
done
[ -e /dev/ppp ] || die "/dev/ppp مفقود — نواة بلا دعم PPP. ثبّت دعم PPP في النواة."
log "/dev/ppp موجود ووحدات PPP محمّلة."

# ── 3b) Bind the management gateway IP to loopback (idempotent + persistent) ──
# accel's [radius] uses nas-ip-address/gw-ip-address = the gateway (10.50.0.1).
# It binds that address as the RADIUS source; if it is not on any interface
# accel dies with `radius:bind: Cannot assign requested address`. We add it to
# `lo` now AND install a oneshot systemd unit so it survives reboot, ordered
# Before=accel-ppp.service so accel always has the address at start.
if command -v ip >/dev/null 2>&1; then
    ip addr replace "${GATEWAY}/32" dev lo \
        && log "عُيِّن ${GATEWAY}/32 على lo." \
        || warn "تعذّر تعيين ${GATEWAY}/32 على lo."
else
    warn "أداة ip غير متوفّرة — لم أستطع تعيين ${GATEWAY}/32 على lo."
fi
IP_BIN="$(command -v ip || echo /sbin/ip)"
UNIT=/etc/systemd/system/hoberadius-accel-mgmt-ip.service
if command -v systemctl >/dev/null 2>&1; then
    NEW_UNIT="$(cat <<UNITEOF
[Unit]
Description=HobeRadius accel mgmt gateway IP on loopback (${GATEWAY}/32)
Before=accel-ppp.service
DefaultDependencies=no
After=network-pre.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=${IP_BIN} addr replace ${GATEWAY}/32 dev lo
ExecStop=${IP_BIN} addr del ${GATEWAY}/32 dev lo

[Install]
WantedBy=multi-user.target
UNITEOF
)"
    # Write only when changed (idempotent — avoids needless daemon-reload).
    if [ ! -f "$UNIT" ] || [ "$(cat "$UNIT")" != "$NEW_UNIT" ]; then
        printf '%s\n' "$NEW_UNIT" > "$UNIT"
        systemctl daemon-reload
        log "كُتبت وحدة systemd لعنوان loopback → $UNIT"
    fi
    systemctl enable hoberadius-accel-mgmt-ip.service >/dev/null 2>&1 || true
    systemctl start  hoberadius-accel-mgmt-ip.service >/dev/null 2>&1 || true
fi

# ── 4) Self-signed SSTP certificate + key (idempotent) ───────────────────────
# Mint cert + key as SEPARATE files. A combined pemfile minted with
# `-keyout f -out f` is unreliable (the cert write truncates the key), which
# leaves accel with no usable private key → TLS handshake fails + `-t` warns.
# Re-mint if EITHER file is missing (or the key is empty) so a broken combined
# pemfile from an earlier run is healed on the next pass.
mkdir -p "$(dirname "$PEMFILE")" "$(dirname "$KEYFILE")"
NEED_CERT=0
{ [ ! -s "$PEMFILE" ] || [ ! -s "$KEYFILE" ]; } && NEED_CERT=1
# Heal a legacy combined pemfile that lacks a separate private key file.
if [ -s "$PEMFILE" ] && [ ! -s "$KEYFILE" ]; then
    warn "الشهادة موجودة بلا ملف مفتاح منفصل — أُعيد توليد الزوج (سبب فشل مصافحة TLS)."
fi
if [ "$NEED_CERT" = 1 ]; then
    log "توليد شهادة + مفتاح SSTP موقّعَين ذاتيًّا → cert=$PEMFILE key=$KEYFILE"
    CMD="$(gen openssl-cmd)" || die "تعذّر توليد أمر الشهادة."
    eval "$CMD" || die "فشل توليد الشهادة/المفتاح."
    chmod 600 "$KEYFILE"
    chmod 644 "$PEMFILE"
else
    log "الشهادة والمفتاح موجودان — يُتركان كما هما."
fi
# Sanity: the cert file must hold a certificate and the key file a private key.
if command -v openssl >/dev/null 2>&1; then
    openssl x509 -in "$PEMFILE" -noout >/dev/null 2>&1 \
        || warn "ملف الشهادة $PEMFILE لا يبدو شهادة X.509 صالحة."
    grep -q 'PRIVATE KEY' "$KEYFILE" 2>/dev/null \
        || warn "ملف المفتاح $KEYFILE لا يحوي مفتاحًا خاصًّا."
fi

# ── 5) Back up existing config ───────────────────────────────────────────────
if [ -f "$CONF" ]; then
    BACKUP="${CONF}.bak.$(date +%Y%m%d-%H%M%S)"
    cp -a "$CONF" "$BACKUP"
    log "نُسخ الإعداد القديم احتياطيًّا → $BACKUP"
fi

# ── 6) Generate config + assert single-section / no-TLS-pin invariants ───────
TMP="$TMPDIR_RUN/accel-ppp.conf"
gen config --out "$TMP" || die "فشل توليد الإعداد."
[ -s "$TMP" ] || die "المولّد أنتج ملفًّا فارغًا."

for section in '[modules]' '[radius]' '[auth]' '[client-ip-range]' '[sstp]' '[ip-pool]'; do
    count="$(grep -cF "$section" "$TMP" || true)"
    [ "$count" -le 1 ] || die "القسم $section مكرّر ($count مرّات) — خلل في المولّد."
done
if grep -Eq '^\s*ssl-(protocol|ciphers)\s*=' "$TMP"; then
    die "الإعداد المولّد يثبّت ssl-protocol/ssl-ciphers — هذا يكسر تفاوض MikroTik."
fi
log "الإعداد المولّد صحيح (لا أقسام مكرّرة، لا تثبيت TLS مقيِّد)."

# Idempotency: only replace when content actually changed.
if [ -f "$CONF" ] && cmp -s "$TMP" "$CONF"; then
    log "الإعداد مطابق سلفًا — لا تغيير."
else
    install -m 0644 "$TMP" "$CONF"
    log "كُتب $CONF"
fi

# ── 7) Validate + (re)start ──────────────────────────────────────────────────
if command -v accel-pppd >/dev/null 2>&1; then
    accel-pppd -t -c "$CONF" >/dev/null 2>&1 && log "فحص بناء الإعداد نجح." \
        || warn "accel-pppd -t أبلغ تحذيرًا — راجع السجل."
fi
if command -v systemctl >/dev/null 2>&1; then
    systemctl enable accel-ppp >/dev/null 2>&1 || true
    systemctl restart accel-ppp || die "تعذّر إعادة تشغيل accel-ppp."
    log "أُعيد تشغيل accel-ppp."
fi

# ── 7b) FreeRADIUS client for accel (auto-provisioned, single secret source) ──
# accel talks RADIUS to FreeRADIUS FROM the gateway IP. FreeRADIUS rejects an
# `unknown client` unless that IP is a defined client. The freeradius container
# auto-loads every .conf under /data/freeradius-clients-wizard/ (see clients.conf
# `$INCLUDE`), which is the host's instance/freeradius-clients-wizard/. We write
# ONE client file there with the SAME secret accel uses (RAD_SECRET above) and
# touch .reload-trigger so the container's watcher reloads (~5s). We do NOT add
# this to /etc/freeradius/clients.conf — that would be a duplicate client.
FR_CLIENTS_DIR="${HOBERADIUS_FR_CLIENTS_DIR:-$REPO/instance/freeradius-clients-wizard}"
if mkdir -p "$FR_CLIENTS_DIR" 2>/dev/null; then
    CLIENT_FILE="$FR_CLIENTS_DIR/accel-local-sstp.conf"
    NEW_CLIENT="$(cat <<CLIENTEOF
# GENERATED by install-accel-selfsigned.sh — accel-ppp RADIUS client.
# secret MUST match accel [radius] (single source: the generator's radius_secret).
client accel_local_sstp {
    ipaddr    = ${GATEWAY}
    secret    = ${RAD_SECRET}
    require_message_authenticator = no
    shortname = accel-local-sstp
    nas_type  = other
}
CLIENTEOF
)"
    if [ ! -f "$CLIENT_FILE" ] || [ "$(cat "$CLIENT_FILE")" != "$NEW_CLIENT" ]; then
        printf '%s\n' "$NEW_CLIENT" > "$CLIENT_FILE"
        touch "$FR_CLIENTS_DIR/.reload-trigger"
        log "كُتب عميل FreeRADIUS لـaccel (${GATEWAY}) → $CLIENT_FILE (سيُعاد التحميل تلقائيًّا)."
    else
        log "عميل FreeRADIUS لـaccel موجود ومطابق — لا تغيير."
    fi
    # Guard: a stray .bak in an $INCLUDE dir makes FreeRADIUS load it too →
    # duplicate-client fatal. Refuse to leave any behind.
    find "$FR_CLIENTS_DIR" -maxdepth 1 -name '*.bak' -type f -delete 2>/dev/null || true
else
    warn "تعذّر إنشاء $FR_CLIENTS_DIR — وفّر عميل FreeRADIUS لـaccel يدويًّا (ipaddr=${GATEWAY}, secret يطابق accel)."
fi

# ── 8) Startup health checks ─────────────────────────────────────────────────
log "فحوصات الإقلاع:"
sleep 1

# listener active?
if command -v ss >/dev/null 2>&1; then
    if ss -ltnH "sport = :${SSTP_PORT}" | grep -q .; then
        log "  ✔ مستمع SSTP نشط على ${SSTP_PORT}"
    else
        warn "  ✘ لا مستمع على ${SSTP_PORT} — accel لم يُقلع؟"
    fi
fi

# TLS handshake — probe like a real RouterOS SSTP client: TLS 1.2, self-signed
# cert (we do NOT verify the chain — RouterOS sets verify-server-certificate=no).
# Success signal = a populated `Master-Key:` line, which only appears when the
# handshake actually COMPLETED. This is self-signed-safe: the verify return code
# being 18 (self-signed) is irrelevant — the session key still gets established.
# (The old probe keyed on a `Cipher :`/`BEGIN CERTIFICATE` line, which could
# both false-pass on `(NONE)` and false-fail on some openssl output formats.)
if command -v openssl >/dev/null 2>&1; then
    TLS_OUT="$(echo Q | timeout 7 openssl s_client -connect "127.0.0.1:${SSTP_PORT}" -tls1_2 2>/dev/null || true)"
    if printf '%s\n' "$TLS_OUT" | grep -qE 'Master-Key[[:space:]]*:[[:space:]]*[0-9A-Fa-f]{16,}'; then
        CIPHER="$(printf '%s\n' "$TLS_OUT" | sed -n 's/.*Cipher[[:space:]]*:[[:space:]]*\([A-Za-z0-9_-]*\).*/\1/p' | grep -viE '^(NONE|0000)?$' | head -n1)"
        log "  ✔ مصافحة TLS 1.2 نجحت (cipher=${CIPHER:-?}، شهادة موقّعة ذاتيًّا مقبولة)."
    else
        warn "  ✘ مصافحة TLS فشلت على ${SSTP_PORT} — تحقّق من ssl-pemfile/ssl-keyfile وسجلّ accel-ppp.log."
    fi
fi

# RADIUS test-user (optional — needs a provisioned rtr- account + secret).
if [ -n "${ACCEL_TEST_USER:-}" ] && command -v radtest >/dev/null 2>&1; then
    if radtest -t mschap "${ACCEL_TEST_USER}" "${ACCEL_TEST_PASS:-}" 127.0.0.1 0 "$RAD_SECRET" 2>/dev/null | grep -q 'Access-Accept'; then
        log "  ✔ اختبار دخول MSCHAP لـ${ACCEL_TEST_USER} نجح."
    else
        warn "  ✘ اختبار دخول MSCHAP لـ${ACCEL_TEST_USER} فشل — تحقّق من rtr- في radcheck + سرّ RADIUS."
    fi
fi

log "تمّ. نفق إدارة v6 (SSTP:${SSTP_PORT}/PPTP:1723) جاهز."
