#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# install-accel-selfsigned.sh — deterministic, idempotent accel-ppp setup for
# the v6 router MANAGEMENT tunnel (SSTP :443 / PPTP :1723).
#
# Replaces the old manual sed/append workflow that produced duplicated
# [radius]/[auth]/[client-ip-range] sections and an over-restrictive TLS policy
# (ssl-protocol=tlsv1.2 + ssl-ciphers=AES256-SHA → MikroTik "ssl: no common
# version (6)").
#
# The config is generated by a STDLIB-ONLY script
# (deploy/accel-ppp/accel_conf_gen.py) — it imports nothing but the Python
# standard library, so this runs with plain host `python3` even when the panel
# runs inside Docker (Flask lives in the container; accel-ppp binds host :443).
# No venv, no `import app`, no Flask required on the host.
#
# Parameter sources (highest precedence first): explicit env on this shell →
# --env-file → an optional docker-exec export of the panel's effective settings
# → built-in defaults. We:
#   1. (optional) pull the panel's effective params via `docker exec` so values
#      set ONLY in the UI propagate without the host needing Flask,
#   2. detect a :443 conflict (nginx/docker) and refuse to clobber it,
#   3. ensure /dev/ppp + PPP kernel modules,
#   4. mint a self-signed SSTP cert if missing,
#   5. back up any existing /etc/accel-ppp.conf (timestamped),
#   6. write the generated config + assert no duplicate sections / no TLS pin,
#   7. (re)start accel-ppp,
#   8. run startup health checks (listener, TLS handshake, radtest mschap).
#
# Safe to run repeatedly. Requires root. Env overrides (all optional):
#   HOBERADIUS_REPO            path to the repo (default: autodetect from script)
#   HOBERADIUS_ACCEL_CONF      target conf path (default: /etc/accel-ppp.conf)
#   HOBERADIUS_ENV_FILE        explicit KEY=VALUE file to feed the generator
#   HOBERADIUS_PANEL_CONTAINER panel container name/id for the param export
#                              (default: autodetect a 'hoberadius' container)
#   HOBERADIUS_NO_DOCKER_EXPORT=1   skip the docker-exec param export
#   ACCEL_TEST_USER / ACCEL_TEST_PASS   radtest mschap probe (optional)
#   PYTHON                     host python3 to use (default: python3)
# Per-key overrides also accepted by the generator and passed through if set:
#   HOBERADIUS_MGMT_TUNNEL_POOL / _SERVER_IP, HOBERADIUS_ACCEL_SSTP_PORT,
#   HOBERADIUS_ACCEL_RADIUS_SERVER / _SECRET, HOBERADIUS_ACCEL_SSL_PEMFILE
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

log()  { printf '\033[1;34m[accel]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[accel WARN]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m[accel FAIL]\033[0m %s\n' "$*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "يجب تشغيله بصلاحيات root."

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="${HOBERADIUS_REPO:-$(cd "$SCRIPT_DIR/../.." && pwd)}"
CONF="${HOBERADIUS_ACCEL_CONF:-/etc/accel-ppp.conf}"
PYBIN="${PYTHON:-python3}"
GEN="$SCRIPT_DIR/accel_conf_gen.py"

[ -f "$GEN" ] || die "مولّد الإعداد غير موجود: $GEN"
command -v docker >/dev/null 2>&1 && DOCKER_OK=1 || DOCKER_OK=0

# Panel container (Docker deployment): used for the optional param export and
# as the no-host-python fallback interpreter. Name is `hoberadius` by default.
PANEL_CID="${HOBERADIUS_PANEL_CONTAINER:-}"
if [ -z "$PANEL_CID" ] && [ "$DOCKER_OK" = 1 ]; then
    PANEL_CID="$(docker ps --filter "name=hoberadius" -q 2>/dev/null | head -n1)"
fi

# Interpreter strategy: PREFER host python3 + the stdlib generator (zero deps,
# no Flask). Only if host python3 is missing do we fall back to running the
# panel container's app (Flask lives there) — same output, reads UI-set DB
# params directly. The stdlib CLI never needs an app context.
HOSTPY=""
if command -v "$PYBIN" >/dev/null 2>&1; then HOSTPY="$PYBIN"; fi
if [ -z "$HOSTPY" ]; then
    { [ "$DOCKER_OK" = 1 ] && [ -n "$PANEL_CID" ]; } \
        || die "لا $PYBIN على المضيف ولا حاوية لوحة (hoberadius) متاحة لتشغيل المولّد."
    warn "لا python3 على المضيف — أشغّل المولّد عبر حاوية اللوحة ${PANEL_CID}."
fi

TMPDIR_RUN="$(mktemp -d)"
trap 'rm -rf "$TMPDIR_RUN"' EXIT

# ── 0a) env-file + optional UI-param export (host-python path only; the ───────
#         container fallback reads the DB directly, so it needs neither).
ENV_FILE=""
if [ -n "$HOSTPY" ]; then
    for cand in "${HOBERADIUS_ENV_FILE:-}" "$REPO/.env" /opt/hoberadius/.env \
                /etc/hoberadius/.env /etc/hoberadius.env; do
        if [ -n "$cand" ] && [ -f "$cand" ]; then ENV_FILE="$cand"; break; fi
    done
    # Values set ONLY in the panel UI live in the (encrypted) DB, which host
    # python3 cannot read. If a panel container is reachable, ask it (Flask is
    # available there) to print KEY=VALUE lines and feed THAT to the stdlib
    # generator. Never blocks: any failure falls back to env-file/env/defaults.
    if [ "${HOBERADIUS_NO_DOCKER_EXPORT:-0}" != "1" ] && [ "$DOCKER_OK" = 1 ] && [ -n "$PANEL_CID" ]; then
        EXPORTED="$TMPDIR_RUN/panel.env"
        if docker exec "$PANEL_CID" python3 -c \
            "from app.radius.services import accel_config as ac; print(chr(10).join(ac.export_env_lines()))" \
            > "$EXPORTED" 2>/dev/null && [ -s "$EXPORTED" ]; then
            ENV_FILE="$EXPORTED"
            log "صُدّرت إعدادات اللوحة الفعليّة من الحاوية $PANEL_CID."
        else
            warn "تعذّر تصدير إعدادات اللوحة من الحاوية — أعتمد env-file/env/الافتراضات."
        fi
    fi
fi

ENV_ARG=()
[ -n "$ENV_FILE" ] && { ENV_ARG=(--env-file "$ENV_FILE"); log "ملف الإعدادات: $ENV_FILE"; }

# gen <subcommand...> — host stdlib generator if python3 exists, else the panel
# container's app (path-independent; reads UI-set DB params).
gen() {
    if [ -n "$HOSTPY" ]; then
        "$HOSTPY" "$GEN" "${ENV_ARG[@]}" "$@"
    else
        _gen_via_container "$@"
    fi
}
_gen_via_container() {
    case "$1" in
        config)
            docker exec -i "$PANEL_CID" python3 -c \
"from app.radius.services import accel_config as ac,sys; sys.stdout.write(ac.generate_accel_conf(ac.params_from_settings()))" ;;
        print)
            docker exec -i "$PANEL_CID" python3 -c \
"from app.radius.services import accel_config as ac; print(getattr(ac.params_from_settings(), '$2'))" ;;
        openssl-cmd)
            docker exec -i "$PANEL_CID" python3 -c \
"from app.radius.services import accel_config as ac,shlex; print(' '.join(shlex.quote(a) for a in ac.openssl_selfsigned_cmd(ac.params_from_settings().ssl_pemfile)))" ;;
        *) die "أمر مولّد غير معروف: $1" ;;
    esac
}

# ── 1) Resolve params from the stdlib generator (no Flask) ────────────────────
SSTP_PORT="$(gen print sstp_port)"  || die "تعذّر حساب منفذ SSTP."
PEMFILE="$(gen print ssl_pemfile)"  || die "تعذّر حساب مسار الشهادة."
log "منفذ SSTP=${SSTP_PORT}  شهادة=${PEMFILE}"

# ── 2) Port conflict detection — accel-pppd is OURS, not a conflict ───────────
# A normal re-run finds :443 held by accel-pppd (our own SSTP server, which we
# restart below). That must NOT abort. We only refuse when a FOREIGN process
# (nginx, docker-proxy, apache, …) holds the port.
if command -v ss >/dev/null 2>&1; then
    HOLDERS="$(ss -ltnpH "sport = :${SSTP_PORT}" 2>/dev/null \
        | grep -oE 'users:\(\("[^"]+"' | grep -oE '"[^"]+"' | tr -d '"' | sort -u)"
    FOREIGN=""
    for h in $HOLDERS; do
        case "$h" in
            accel-pppd|accel-ppp) : ;;            # our SSTP server — fine
            *) FOREIGN="$FOREIGN $h" ;;
        esac
    done
    FOREIGN="$(printf '%s' "$FOREIGN" | tr -s ' ' | sed -e 's/^ //' -e 's/ $//')"
    if [ -n "$FOREIGN" ]; then
        die "منفذ ${SSTP_PORT} مشغول بعملية أجنبية: ${FOREIGN}. أوقفها (nginx/docker-proxy/apache على هذا المنفذ) ثم أعد التشغيل — مستمع SSTP يحتاج المنفذ. ملاحظة: إن كانت حاوية nginx تنشر :443 في docker-compose، أزِل خريطة \"443:443\" منها لتحرير المنفذ لـaccel على المضيف."
    fi
    if [ -n "$HOLDERS" ]; then
        log "منفذ ${SSTP_PORT} يملكه accel-pppd (خادمنا) — سيُعاد تشغيله، ليس تعارضًا."
    else
        log "منفذ ${SSTP_PORT} متاح."
    fi
else
    log "ss غير متوفّر — تخطّي فحص تعارض المنفذ."
fi

# ── 3) /dev/ppp + kernel modules ─────────────────────────────────────────────
for mod in ppp_generic ppp_async ppp_synctty ppp_mppe; do
    modprobe "$mod" 2>/dev/null || warn "تعذّر تحميل وحدة $mod (قد تكون مدمجة في النواة)."
done
[ -e /dev/ppp ] || die "/dev/ppp مفقود — نواة بلا دعم PPP. ثبّت دعم PPP في النواة."
log "/dev/ppp موجود ووحدات PPP محمّلة."

# ── 4) Self-signed SSTP certificate (idempotent) ─────────────────────────────
mkdir -p "$(dirname "$PEMFILE")"
if [ ! -s "$PEMFILE" ]; then
    log "توليد شهادة SSTP موقّعة ذاتيًّا → $PEMFILE"
    CMD="$(gen openssl-cmd)" || die "تعذّر توليد أمر الشهادة."
    eval "$CMD" || die "فشل توليد الشهادة."
    chmod 600 "$PEMFILE"
else
    log "الشهادة موجودة — تُترك كما هي."
fi

# ── 5) Back up existing config ───────────────────────────────────────────────
if [ -f "$CONF" ]; then
    BACKUP="${CONF}.bak.$(date +%Y%m%d-%H%M%S)"
    cp -a "$CONF" "$BACKUP"
    log "نُسخ الإعداد القديم احتياطيًّا → $BACKUP"
fi

# ── 6) Generate config + assert single-section / no-TLS-pin invariants ───────
TMP="$TMPDIR_RUN/accel-ppp.conf"
gen config --out "$TMP" || die "فشل توليد الإعداد."
[ -s "$TMP" ] || die "المولّد أنتج ملفًّا فارغًا."

for section in '[modules]' '[radius]' '[auth]' '[client-ip-range]' '[sstp]' '[ip-pool]'; do
    count="$(grep -cF "$section" "$TMP" || true)"
    [ "$count" -le 1 ] || die "القسم $section مكرّر ($count مرّات) — خلل في المولّد."
done
if grep -Eq '^\s*ssl-(protocol|ciphers)\s*=' "$TMP"; then
    die "الإعداد المولّد يثبّت ssl-protocol/ssl-ciphers — هذا يكسر تفاوض MikroTik."
fi
log "الإعداد المولّد صحيح (لا أقسام مكرّرة، لا تثبيت TLS مقيِّد)."

# Idempotency: only replace when content actually changed.
if [ -f "$CONF" ] && cmp -s "$TMP" "$CONF"; then
    log "الإعداد مطابق سلفًا — لا تغيير."
else
    install -m 0644 "$TMP" "$CONF"
    log "كُتب $CONF"
fi

# ── 7) Validate + (re)start ──────────────────────────────────────────────────
if command -v accel-pppd >/dev/null 2>&1; then
    accel-pppd -t -c "$CONF" >/dev/null 2>&1 && log "فحص بناء الإعداد نجح." \
        || warn "accel-pppd -t أبلغ تحذيرًا — راجع السجل."
fi
if command -v systemctl >/dev/null 2>&1; then
    systemctl enable accel-ppp >/dev/null 2>&1 || true
    systemctl restart accel-ppp || die "تعذّر إعادة تشغيل accel-ppp."
    log "أُعيد تشغيل accel-ppp."
fi

# ── 8) Startup health checks ─────────────────────────────────────────────────
log "فحوصات الإقلاع:"
sleep 1

# listener active?
if command -v ss >/dev/null 2>&1; then
    if ss -ltnH "sport = :${SSTP_PORT}" | grep -q .; then
        log "  ✔ مستمع SSTP نشط على ${SSTP_PORT}"
    else
        warn "  ✘ لا مستمع على ${SSTP_PORT} — accel لم يُقلع؟"
    fi
fi

# TLS handshake (let OpenSSL negotiate; expect a cipher to be chosen).
if command -v openssl >/dev/null 2>&1; then
    if echo | timeout 5 openssl s_client -connect "127.0.0.1:${SSTP_PORT}" 2>/dev/null \
            | grep -Eq 'Cipher\s*:\s*\S'; then
        CIPHER="$(echo | timeout 5 openssl s_client -connect "127.0.0.1:${SSTP_PORT}" 2>/dev/null | sed -n 's/.*Cipher\s*:\s*\(\S*\).*/\1/p' | head -n1)"
        log "  ✔ مصافحة TLS نجحت (cipher=${CIPHER:-?})"
    else
        warn "  ✘ مصافحة TLS فشلت على ${SSTP_PORT}"
    fi
fi

# RADIUS test-user (optional — needs a provisioned rtr- account + secret).
if [ -n "${ACCEL_TEST_USER:-}" ] && command -v radtest >/dev/null 2>&1; then
    RAD_SECRET="$(gen print radius_secret)"
    if radtest -t mschap "${ACCEL_TEST_USER}" "${ACCEL_TEST_PASS:-}" 127.0.0.1 0 "$RAD_SECRET" 2>/dev/null | grep -q 'Access-Accept'; then
        log "  ✔ اختبار دخول MSCHAP لـ${ACCEL_TEST_USER} نجح."
    else
        warn "  ✘ اختبار دخول MSCHAP لـ${ACCEL_TEST_USER} فشل — تحقّق من rtr- في radcheck + سرّ RADIUS."
    fi
fi

log "تمّ. نفق إدارة v6 (SSTP:${SSTP_PORT}/PPTP:1723) جاهز."
