"""
ثوابت HobeRadius — domain values فقط (لا env).
"""
from __future__ import annotations

# ────────────────────────── حالات عامة ──────────────────────────

STATUS_ENABLED = "enabled"
STATUS_DISABLED = "disabled"
STATUS_EXPIRED = "expired"
STATUS_SUSPENDED = "suspended"
STATUS_PENDING = "pending"

ACCOUNT_STATUSES = (STATUS_ENABLED, STATUS_DISABLED, STATUS_EXPIRED, STATUS_SUSPENDED, STATUS_PENDING)

# ────────────────────────── أوضاع الـ Adapter ──────────────────────────

ADAPTER_MODE_MANUAL = "manual"
ADAPTER_MODE_API = "api"
ADAPTER_MODE_DIRECT = "direct"
ADAPTER_MODE_SQLITE = "sqlite"

ADAPTER_MODES = (ADAPTER_MODE_MANUAL, ADAPTER_MODE_API, ADAPTER_MODE_DIRECT, ADAPTER_MODE_SQLITE)

# ────────────────────────── أنواع NAS ──────────────────────────

NAS_VENDOR_MIKROTIK = "mikrotik"
NAS_VENDOR_CISCO = "cisco"
NAS_VENDOR_HUAWEI = "huawei"
NAS_VENDOR_UBIQUITI = "ubiquiti"
NAS_VENDOR_OTHER = "other"
NAS_VENDORS = (NAS_VENDOR_MIKROTIK, NAS_VENDOR_CISCO, NAS_VENDOR_HUAWEI, NAS_VENDOR_UBIQUITI, NAS_VENDOR_OTHER)

NAS_TYPE_HOTSPOT = "hotspot"
NAS_TYPE_PPPOE = "pppoe"
NAS_TYPE_DHCP = "dhcp"
NAS_TYPE_OTHER = "other"
NAS_TYPES = (NAS_TYPE_HOTSPOT, NAS_TYPE_PPPOE, NAS_TYPE_DHCP, NAS_TYPE_OTHER)

# ────────────────────────── أنواع الباقات/العروض ──────────────────────────

PLAN_TYPE_TIME = "time"
PLAN_TYPE_QUOTA = "quota"
PLAN_TYPE_HYBRID = "hybrid"
PLAN_TYPE_UNLIMITED = "unlimited"
PLAN_TYPE_RECURRING = "recurring"
PLAN_TYPES = (PLAN_TYPE_TIME, PLAN_TYPE_QUOTA, PLAN_TYPE_HYBRID, PLAN_TYPE_UNLIMITED, PLAN_TYPE_RECURRING)

# ────────────────────────── أنواع المستخدمين ──────────────────────────

USER_TYPE_SUBSCRIBER = "subscriber"
USER_TYPE_CARD = "card"
USER_TYPE_TRIAL = "trial"
USER_TYPES = (USER_TYPE_SUBSCRIBER, USER_TYPE_CARD, USER_TYPE_TRIAL)

# ────────────────────────── سجلات التدقيق ──────────────────────────

AUDIT_ACTION_CREATE = "create"
AUDIT_ACTION_UPDATE = "update"
AUDIT_ACTION_DELETE = "delete"
AUDIT_ACTION_DISCONNECT = "disconnect"
AUDIT_ACTION_RESET_PASSWORD = "reset_password"
AUDIT_ACTION_DISABLE = "disable"
AUDIT_ACTION_ENABLE = "enable"
AUDIT_ACTION_LOGIN = "login"
AUDIT_ACTION_LOGOUT = "logout"
AUDIT_ACTION_BATCH_GENERATE = "batch_generate"
AUDIT_ACTION_REVOKE = "revoke"
AUDIT_ACTION_ARCHIVE = "archive"
AUDIT_ACTION_RESTORE = "restore"
AUDIT_ACTION_VOID = "void"
AUDIT_ACTION_REVERSAL = "reversal"
AUDIT_ACTION_SETTLEMENT = "settlement"
AUDIT_ACTION_LOAN_GRANT = "loan_grant"
AUDIT_ACTION_LOAN_SETTLE = "loan_settle"
AUDIT_ACTION_PAYMENT_RECORD = "payment_record"
AUDIT_ACTION_CARD_CHECK = "card_check"
AUDIT_ACTION_BATCH_ARCHIVE = "batch_archive"
AUDIT_ACTION_BATCH_RESTORE = "batch_restore"
AUDIT_ACTION_LEDGER_POST = "ledger_post"
AUDIT_ACTION_LEDGER_VOID = "ledger_void"

AUDIT_SCHEMA_CUSTOMER_ROADMAP_V1 = "customer-roadmap.audit.v1"

CUSTOMER_ROADMAP_AUDIT_ACTIONS: tuple[str, ...] = (
    AUDIT_ACTION_ARCHIVE,
    AUDIT_ACTION_RESTORE,
    AUDIT_ACTION_VOID,
    AUDIT_ACTION_REVERSAL,
    AUDIT_ACTION_SETTLEMENT,
    AUDIT_ACTION_LOAN_GRANT,
    AUDIT_ACTION_LOAN_SETTLE,
    AUDIT_ACTION_PAYMENT_RECORD,
    AUDIT_ACTION_CARD_CHECK,
    AUDIT_ACTION_BATCH_ARCHIVE,
    AUDIT_ACTION_BATCH_RESTORE,
    AUDIT_ACTION_LEDGER_POST,
    AUDIT_ACTION_LEDGER_VOID,
)

LEDGER_TYPE_PAYMENT = "payment"
LEDGER_TYPE_LOAN = "loan"
LEDGER_TYPE_SETTLEMENT = "settlement"
LEDGER_TYPE_VOID = "void"
LEDGER_TYPE_REVERSAL = "reversal"
LEDGER_TYPE_CORRECTION = "correction"
LEDGER_TYPES: tuple[str, ...] = (
    LEDGER_TYPE_PAYMENT,
    LEDGER_TYPE_LOAN,
    LEDGER_TYPE_SETTLEMENT,
    LEDGER_TYPE_VOID,
    LEDGER_TYPE_REVERSAL,
    LEDGER_TYPE_CORRECTION,
)

LEDGER_STATUS_POSTED = "posted"
LEDGER_STATUS_VOID = "void"
LEDGER_STATUS_REVERSAL = "reversal"
LEDGER_STATUSES: tuple[str, ...] = (
    LEDGER_STATUS_POSTED,
    LEDGER_STATUS_VOID,
    LEDGER_STATUS_REVERSAL,
)

LOAN_STATUS_OPEN = "open"
LOAN_STATUS_SETTLED = "settled"
LOAN_STATUS_VOIDED = "voided"
LOAN_STATUSES: tuple[str, ...] = (
    LOAN_STATUS_OPEN,
    LOAN_STATUS_SETTLED,
    LOAN_STATUS_VOIDED,
)

PAYMENT_STATUS_POSTED = "posted"
PAYMENT_STATUS_VOIDED = "voided"

LIFECYCLE_ACTIVE = "active"
LIFECYCLE_DELETED = "deleted"
LIFECYCLE_ARCHIVED = "archived"
LIFECYCLE_CANCELLED = "cancelled"
LIFECYCLE_STATUSES: tuple[str, ...] = (
    LIFECYCLE_ACTIVE,
    LIFECYCLE_DELETED,
    LIFECYCLE_ARCHIVED,
    LIFECYCLE_CANCELLED,
)

# ────────────────────────── السياسات ──────────────────────────

POLICY_TYPE_RATE_LIMIT = "rate_limit"
POLICY_TYPE_QUOTA = "quota"
POLICY_TYPE_TIME_WINDOW = "time_window"
POLICY_TYPE_CONCURRENT = "concurrent_sessions"
POLICY_TYPES = (POLICY_TYPE_RATE_LIMIT, POLICY_TYPE_QUOTA, POLICY_TYPE_TIME_WINDOW, POLICY_TYPE_CONCURRENT)

# ────────────────────────── الأدوار والصلاحيات ──────────────────────────

PERM_DASHBOARD_VIEW = "dashboard.view"

PERM_USERS_VIEW = "users.view"
PERM_USERS_CREATE = "users.create"
PERM_USERS_EDIT = "users.edit"
PERM_USERS_DELETE = "users.delete"
PERM_USERS_DISCONNECT = "users.disconnect"

PERM_CARDS_VIEW = "cards.view"
PERM_CARDS_GENERATE = "cards.generate"
PERM_CARDS_REVOKE = "cards.revoke"

PERM_PLANS_VIEW = "plans.view"
PERM_PLANS_CREATE = "plans.create"
PERM_PLANS_EDIT = "plans.edit"
PERM_PLANS_DELETE = "plans.delete"

PERM_NAS_VIEW = "nas.view"
PERM_NAS_CREATE = "nas.create"
PERM_NAS_EDIT = "nas.edit"
PERM_NAS_DELETE = "nas.delete"

PERM_SESSIONS_VIEW = "sessions.view"
PERM_SESSIONS_DISCONNECT = "sessions.disconnect"

PERM_ADMINS_VIEW = "admins.view"
PERM_ADMINS_CREATE = "admins.create"
PERM_ADMINS_EDIT = "admins.edit"
PERM_ADMINS_DELETE = "admins.delete"

PERM_SETTINGS_VIEW = "settings.view"
PERM_SETTINGS_EDIT = "settings.edit"
PERM_AUDIT_VIEW = "audit.view"
PERM_API_USE = "api.use"

ALL_PERMISSIONS: tuple[str, ...] = (
    PERM_DASHBOARD_VIEW,
    PERM_USERS_VIEW, PERM_USERS_CREATE, PERM_USERS_EDIT, PERM_USERS_DELETE, PERM_USERS_DISCONNECT,
    PERM_CARDS_VIEW, PERM_CARDS_GENERATE, PERM_CARDS_REVOKE,
    PERM_PLANS_VIEW, PERM_PLANS_CREATE, PERM_PLANS_EDIT, PERM_PLANS_DELETE,
    PERM_NAS_VIEW, PERM_NAS_CREATE, PERM_NAS_EDIT, PERM_NAS_DELETE,
    PERM_SESSIONS_VIEW, PERM_SESSIONS_DISCONNECT,
    PERM_ADMINS_VIEW, PERM_ADMINS_CREATE, PERM_ADMINS_EDIT, PERM_ADMINS_DELETE,
    PERM_SETTINGS_VIEW, PERM_SETTINGS_EDIT, PERM_AUDIT_VIEW,
    PERM_API_USE,
)

ROLE_SUPER_ADMIN = "super_admin"
ROLE_OPERATOR = "operator"
ROLE_SUPPORT = "support"
ROLE_BILLING = "billing"
ROLE_VIEWER = "viewer"

DEFAULT_ROLE_PERMISSIONS = {
    ROLE_SUPER_ADMIN: tuple(ALL_PERMISSIONS),
    ROLE_OPERATOR: (
        PERM_DASHBOARD_VIEW,
        PERM_USERS_VIEW, PERM_USERS_CREATE, PERM_USERS_EDIT, PERM_USERS_DISCONNECT,
        PERM_CARDS_VIEW, PERM_CARDS_GENERATE,
        PERM_PLANS_VIEW, PERM_NAS_VIEW,
        PERM_SESSIONS_VIEW, PERM_SESSIONS_DISCONNECT,
        PERM_AUDIT_VIEW,
    ),
    ROLE_SUPPORT: (
        PERM_DASHBOARD_VIEW,
        PERM_USERS_VIEW, PERM_USERS_DISCONNECT,
        PERM_CARDS_VIEW, PERM_PLANS_VIEW, PERM_NAS_VIEW,
        PERM_SESSIONS_VIEW, PERM_SESSIONS_DISCONNECT,
    ),
    ROLE_BILLING: (PERM_DASHBOARD_VIEW, PERM_USERS_VIEW, PERM_CARDS_VIEW, PERM_PLANS_VIEW),
    ROLE_VIEWER: (PERM_DASHBOARD_VIEW,),
}

# ────────────────────────── حدود نمو ──────────────────────────

DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100
TABLE_FETCH_CAP = 2000
