"""Secure, time-boxed remote access to a router's WinBox (and structurally
SSH/web) over the SSTP management tunnel — driven from the panel.

Mechanism (reuses the proven nginx-stream forwarder the NPC feature uses):
  PANEL_PUBLIC_IP:<allocated_port>  →  <router_tunnel_ip>:<dst_port>
realised as an nginx-stream `server{}` block on the already-published
51000-51199 host range. The panel writes the config to the shared bind-mount
``/etc/hoberadius/nginx-streams.d/`` and touches the reload marker the nginx
sidecar watches. No new host daemon; restart-survives (config persists on host).

Security (production defaults):
  * **Source-IP lock** — every block is ``allow <admin_ip>; deny all;`` so only
    the requesting admin's public IP can connect.
  * **Time-boxed** — an absolute ``expires_at``; a sweep auto-closes and the
    forward is removed. Manual "Close now" too.
  * **Unique port per session**, released on close (allocator avoids the NPC
    pool + active sessions).
  * **Audited** — open/close recorded (admin, router, source IP, timestamps).

The router side is already locked down by the onboarding script: WinBox/mgmt is
reachable ONLY from the tunnel gateway (``/ip service set winbox
address=10.50.0.1/32``) and never the WAN — and our forward reaches the router
SNAT'd as 10.50.0.1, so it matches that restriction.
"""
from __future__ import annotations

import ipaddress
import logging
import os
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Optional

from ..core import env_settings
from ..db.connection import db
from ..db.repos import router_remote_sessions_repo as sess_repo

_LOG = logging.getLogger(__name__)

#: RouterOS-side mgmt ports per service. Phase 1 ships WinBox; the table +
#: renderer already carry `service`/`dst_port` so SSH/web slot in later.
SERVICE_PORTS = {"winbox": 8291, "ssh": 22, "web": 80, "web_ssl": 443}

#: nginx stream config file we own (separate from NPC's npc_remote.conf).
STREAM_FILE = "hr-remote-access.conf"


class RemoteAccessError(ValueError):
    """Bad/unsafe remote-access request."""


# ─── settings ────────────────────────────────────────────────────────────────

def enabled() -> bool:
    return env_settings.get_bool("HOBERADIUS_REMOTE_ACCESS_ENABLED", True)


def always_on_mode() -> bool:
    return env_settings.get_bool("HOBERADIUS_REMOTE_ACCESS_ALWAYS_ON", False)


def ttl_minutes() -> int:
    try:
        v = int(env_settings.env("HOBERADIUS_REMOTE_ACCESS_TTL_MIN", 20))
    except (TypeError, ValueError):
        v = 20
    return max(2, min(v, 1440))   # clamp 2 min .. 24 h


def public_host() -> str:
    for k in ("HOBERADIUS_PUBLIC_IP", "HOBERADIUS_PUBLIC_HOST"):
        v = str(env_settings.env(k, "") or "").strip()
        if v:
            return v
    return ""


def _stream_dir() -> Path:
    raw = (os.environ.get("HOBERADIUS_NGINX_STREAM_DIR")
           or "/etc/hoberadius/nginx-streams.d")
    return Path(raw)


# ─── validation helpers ──────────────────────────────────────────────────────

def _valid_ip(value: str) -> str:
    """Return the validated IP string, or raise. Guards against injection into
    the nginx config — only a real IP can ever be written into allow/proxy."""
    try:
        return str(ipaddress.ip_address(str(value or "").strip()))
    except ValueError as exc:
        raise RemoteAccessError(f"عنوان IP غير صالح: {value!r}") from exc


def router_tunnel_ip(tenant_id: int, router_id: int) -> str:
    """The router's reachable tunnel IP (Framed-IP) for the forward target.
    Prefers the persisted management_remote_address / vpn_peer_address."""
    row = db().execute(
        "SELECT management_remote_address, vpn_peer_address, address "
        "FROM nas_devices WHERE id=? AND tenant_id=? "
        "  AND (deleted_at IS NULL OR deleted_at='')",
        (int(router_id), int(tenant_id))).fetchone()
    if not row:
        raise RemoteAccessError("الراوتر غير موجود")
    r = dict(row)
    for key in ("management_remote_address", "vpn_peer_address"):
        v = str(r.get(key) or "").strip()
        if v:
            return v
    raise RemoteAccessError(
        "لا عنوان نفق لهذا الراوتر — أعِد إعداد نفق SSTP أولًا")


# ─── nginx-stream config generation (source-IP locked) ───────────────────────

def render_stream_config(sessions: list) -> str:
    """Render the stream config for the given ACTIVE sessions. Every block is
    source-IP locked. Invalid rows are skipped (fail-safe — a bad row can never
    open an unrestricted forward)."""
    out = [
        "# GENERATED by HobeRadius router_remote_access — DO NOT edit.",
        "# Per-session WinBox/mgmt forwards, each locked to one admin IP.",
        "",
    ]
    for s in sessions:
        try:
            port = int(s["public_port"])
            tip = _valid_ip(s["tunnel_ip"])
            dport = int(s["dst_port"])
            src = _valid_ip(s["source_ip"])
        except (KeyError, ValueError, RemoteAccessError) as exc:
            _LOG.warning("remote-access: skipping bad session %s: %s",
                         s.get("id"), exc)
            continue
        out += [
            f'# session {s.get("id")} router {s.get("router_id")} '
            f'by {s.get("opened_by")} until {s.get("expires_at")}',
            "server {",
            f"    listen {port};",
            f"    allow {src};",
            "    deny all;",
            f"    proxy_pass {tip}:{dport};",
            "    proxy_connect_timeout 10s;",
            "    proxy_timeout 1h;",
            "}",
            "",
        ]
    return "\n".join(out)


def regenerate_and_reload() -> dict:
    """Rewrite our stream file from ALL active sessions (host-global) + touch the
    nginx reload marker. Atomic write. Never raises on FS issues in prod paths —
    callers wrap; here we surface so the route can report failure."""
    d = _stream_dir()
    d.mkdir(parents=True, exist_ok=True)
    body = render_stream_config(sess_repo.list_active(tenant_id=None))
    out = d / STREAM_FILE
    tmp = out.with_suffix(out.suffix + ".tmp")
    tmp.write_text(body, encoding="utf-8")
    tmp.replace(out)
    (d / ".reload").touch()
    return {"config_path": str(out)}


# ─── lifecycle ───────────────────────────────────────────────────────────────

def _now() -> datetime:
    return datetime.now(timezone.utc)


def _iso(dt: datetime) -> str:
    return dt.strftime("%Y-%m-%dT%H:%M:%SZ")


def open_session(*, tenant_id: int, router_id: int, source_ip: str,
                 opened_by: str, service: str = "winbox",
                 ttl_min: Optional[int] = None,
                 audit=True) -> dict:
    """Open a managed, source-IP-locked, time-boxed forward to the router's
    WinBox (or `service`) over the tunnel. Returns the host:port to paste."""
    if not enabled():
        raise RemoteAccessError("الوصول البعيد مُعطّل في الإعدادات")
    service = (service or "winbox").strip().lower()
    if service not in SERVICE_PORTS:
        raise RemoteAccessError(f"خدمة غير مدعومة: {service!r}")
    src = _valid_ip(source_ip)
    tip = router_tunnel_ip(tenant_id, router_id)
    _valid_ip(tip)  # the persisted tunnel IP must be a real IP

    # One active session per (router, service): reuse/refresh instead of piling
    # up forwards. Close the old one first (it'll be re-added below).
    existing = sess_repo.active_for_router(tenant_id, router_id)
    if existing and str(existing.get("service")) == service:
        sess_repo.mark_closed(existing["id"], reason="reopened")

    persistent = always_on_mode()
    ttl = int(ttl_min) if ttl_min else ttl_minutes()
    expires = _iso(_now() + timedelta(minutes=ttl))
    port = sess_repo.allocate_port()
    sid = sess_repo.create_session(
        tenant_id=tenant_id, router_id=router_id, service=service,
        public_port=port, tunnel_ip=tip, dst_port=SERVICE_PORTS[service],
        source_ip=src, opened_by=opened_by, expires_at=expires,
        always_on=1 if persistent else 0,
    )
    regenerate_and_reload()
    if audit:
        _audit("remote_access_open", router_id, opened_by, src, result="success",
               payload={"session_id": sid, "port": port, "service": service,
                        "tunnel_ip": tip, "expires_at": expires})
    host = public_host()
    return {
        "session_id": sid, "port": port, "host": host, "service": service,
        "tunnel_ip": tip, "expires_at": expires, "source_ip": src,
        "endpoint": (f"{host}:{port}" if host else f"<PANEL_PUBLIC_IP>:{port}"),
    }


def close_session(*, tenant_id: int, session_id: int, closed_by: str,
                  reason: str = "manual", source_ip: str = "") -> bool:
    row = sess_repo.get(session_id)
    if not row or int(row["tenant_id"]) != int(tenant_id):
        return False
    ok = sess_repo.mark_closed(session_id, reason=reason)
    if ok:
        regenerate_and_reload()
        _audit("remote_access_close", row["router_id"], closed_by, source_ip,
               result="success",
               payload={"session_id": session_id, "reason": reason,
                        "port": row.get("public_port")})
    return ok


def sweep_expired() -> int:
    """Close every session past its absolute expiry, regenerate once. Returns the
    count closed. Safe to call frequently; idempotent."""
    expired = sess_repo.list_expired()
    if not expired:
        return 0
    for s in expired:
        sess_repo.mark_closed(s["id"], reason="expired")
    try:
        regenerate_and_reload()
    except OSError:
        _LOG.exception("remote-access sweep: stream regen failed")
    for s in expired:
        _audit("remote_access_expire", s["router_id"], "system", "",
               result="auto", payload={"session_id": s["id"],
                                        "port": s.get("public_port")})
    _LOG.info("remote-access sweep: closed %d expired session(s)", len(expired))
    return len(expired)


def seconds_remaining(session: dict) -> int:
    """Whole seconds until the session's absolute expiry (>=0)."""
    try:
        exp = datetime.strptime(str(session.get("expires_at") or ""),
                                "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=timezone.utc)
    except ValueError:
        return 0
    return max(0, int((exp - _now()).total_seconds()))


def _audit(action: str, router_id, actor: str, source_ip: str, *,
           result: str, payload: dict) -> None:
    """Best-effort audit — never breaks the action."""
    try:
        from .audit import get_audit_service
        get_audit_service().record(
            actor=actor or "system", action=action, target_type="router",
            target_id=str(router_id), router_id=int(router_id),
            severity="warning", result_status=result,
            payload={**payload, "source_ip": source_ip})
    except Exception:  # noqa: BLE001
        _LOG.exception("remote-access audit failed (non-fatal)")


__all__ = [
    "RemoteAccessError", "SERVICE_PORTS", "enabled", "always_on_mode",
    "ttl_minutes", "public_host", "router_tunnel_ip", "render_stream_config",
    "regenerate_and_reload", "open_session", "close_session", "sweep_expired",
    "seconds_remaining",
]
