"""SW-server-side — write FreeRADIUS clients.conf snippet from
the wizard, no SSH required.

After Step 3 the operator has a router talking to 10.10.0.1
with a fresh shared secret. But FreeRADIUS rejects the auth
because clients.conf on the server doesn't know that router.

This service automates the missing piece. Per wizard-run it
writes ONE file:

    /app/instance/freeradius-clients-wizard/wizard-run-<id>.conf

which freeradius sees via the shared `instance/` volume as
`/data/freeradius-clients-wizard/wizard-run-<id>.conf`. The
main `clients.conf` includes that directory:

    $INCLUDE /data/freeradius-clients-wizard/*.conf

After writing, this service touches `.reload-trigger` in the
same directory. The freeradius entrypoint's background
watcher picks that up and SIGTERMs the freeradius process —
the supervisor loop relaunches it and the new client is
loaded. Total reload time: ~5 seconds.

Files in this directory are owned by hoberadius (uid 999) and
group=freerad (gid 101) thanks to the setgid bit the
entrypoint sets on `/data`. Both processes can read+write.

Filename convention pins the file to a specific run, so:
* re-running the wizard on the same run overwrites the file
* retire/abandon flows can remove the file cleanly
* the emergency fleet reset wipes everything matching
  `wizard-run-*.conf`

Safety: refuses to write outside the managed directory.
Refuses to use a secret containing characters that would
break the clients.conf syntax (literal `"` or `}`).
"""
from __future__ import annotations

import logging
import os
import re
import time
from pathlib import Path
from typing import Any


_LOG = logging.getLogger(__name__)


# Default location inside the hoberadius container. The host
# directory `/opt/hoberadius/instance/freeradius-clients-wizard/`
# is bind-mounted to both containers:
#   hoberadius: /app/instance/freeradius-clients-wizard
#   freeradius: /data/freeradius-clients-wizard
_DEFAULT_DIR = Path("/app/instance/freeradius-clients-wizard")
_DIR_ENV = "HOBERADIUS_FREERADIUS_CLIENTS_WIZARD_DIR"


# Sanity-check on the secret + shortname. clients.conf is
# parsed as RouterOS-style key=value blocks — any unescaped
# `"`, `}`, or newline breaks the parser silently.
_UNSAFE = re.compile(r'[\"\}\n\r]')


class FreeRadiusProvisioningError(Exception):
    """Raised when the snippet can't be written safely."""


def _dir() -> Path:
    raw = os.environ.get(_DIR_ENV)
    return Path(raw) if raw else _DEFAULT_DIR


def write_client_for_run(
    *,
    run_id: int,
    router_vpn_ip: str,
    radius_secret: str,
    shortname: str | None = None,
) -> dict[str, Any]:
    """Atomically write the client block for one wizard run.
    Returns a small summary suitable for logging and UI.

    Side effect: removes any existing `wizard-run-*.conf`
    that targets the SAME `router_vpn_ip` but belongs to a
    different run_id. This enforces the invariant
    'one ipaddr → one active client file'. Without this,
    re-running the wizard for the same router (or replacing
    one router with another using the same VPN slot) would
    leave stale entries that may carry an obsolete secret.
    """
    if not router_vpn_ip:
        raise FreeRadiusProvisioningError(
            "router_vpn_ip is required",
        )
    if not radius_secret:
        raise FreeRadiusProvisioningError(
            "radius_secret is required",
        )
    if _UNSAFE.search(radius_secret):
        raise FreeRadiusProvisioningError(
            "radius_secret contains characters that break "
            "clients.conf parsing (\", }, or newline)",
        )

    target_dir = _dir()
    try:
        target_dir.mkdir(parents=True, exist_ok=True)
    except PermissionError as exc:
        raise FreeRadiusProvisioningError(
            f"cannot create {target_dir} — fix host volume "
            f"permissions: {exc}",
        ) from exc

    # Enforce 1-ip → 1-file. Wipe any stale file for this IP
    # that belongs to a different run BEFORE writing the new
    # one (so two runs for the same router can't both have
    # files claiming the same client IP).
    _purge_stale_files_for_ip(
        target_dir, router_vpn_ip, except_run_id=run_id,
    )

    short = shortname or f"wizard-router-{int(run_id)}"
    # FreeRADIUS shortnames + client-block names must be safe
    # identifiers — strip anything weird.
    safe_short = re.sub(r"[^A-Za-z0-9_-]+", "-", short)[:48] or f"r{run_id}"

    block = (
        f"# AUTO-GENERATED by HobeRadius Setup Wizard v3\n"
        f"# Wizard run: {int(run_id)}\n"
        f"# Generated at: {time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())}\n"
        f"# DO NOT EDIT — the wizard will overwrite on re-run.\n"
        f"# Remove this file to revoke the router's RADIUS access.\n"
        f"\n"
        f"client router-{int(run_id)} {{\n"
        f"    ipaddr      = {router_vpn_ip}\n"
        f"    secret      = {radius_secret}\n"
        f"    require_message_authenticator = no\n"
        f"    nas_type    = mikrotik\n"
        f"    shortname   = {safe_short}\n"
        f"}}\n"
    )

    target = target_dir / f"wizard-run-{int(run_id)}.conf"
    # Resolve and double-check we're still under the managed
    # directory — defends against any future bug where a
    # tainted run_id could escape.
    resolved = target.resolve()
    if not str(resolved).startswith(str(target_dir.resolve())):
        raise FreeRadiusProvisioningError(
            "refusing to write outside the managed directory",
        )

    tmp = target.with_suffix(".conf.tmp")
    try:
        tmp.write_text(block, encoding="utf-8")
        tmp.replace(target)  # atomic rename
    except PermissionError as exc:
        raise FreeRadiusProvisioningError(
            f"cannot write {target}: {exc}",
        ) from exc

    # Touch the reload trigger so the freeradius entrypoint's
    # watcher picks up the change. Idempotent — repeat writes
    # just bump the mtime.
    trigger = target_dir / ".reload-trigger"
    try:
        trigger.touch(exist_ok=True)
        # Bump mtime explicitly even if file existed.
        now = time.time()
        os.utime(trigger, (now, now))
    except Exception:  # noqa: BLE001
        _LOG.warning(
            "could not touch reload trigger %s — operator may "
            "need to restart freeradius manually",
            trigger,
            exc_info=True,
        )

    return {
        "status": "written",
        "path_in_hoberadius": str(target),
        "path_in_freeradius": str(target).replace(
            "/app/instance/", "/data/",
        ),
        "shortname": safe_short,
        "reload_trigger": str(trigger),
        "expected_reload_seconds": 5,
    }


def remove_client_for_run(
    *, run_id: int,
) -> dict[str, Any]:
    """Delete the client block for one wizard run. Used by the
    retire/abandon/emergency-reset flows."""
    target = _dir() / f"wizard-run-{int(run_id)}.conf"
    if not target.exists():
        return {"status": "absent", "path": str(target)}
    try:
        target.unlink()
    except Exception as exc:  # noqa: BLE001
        raise FreeRadiusProvisioningError(
            f"cannot remove {target}: {exc}",
        ) from exc
    # Trigger reload to drop the revoked client.
    trigger = _dir() / ".reload-trigger"
    try:
        trigger.touch(exist_ok=True)
        now = time.time()
        os.utime(trigger, (now, now))
    except Exception:  # noqa: BLE001
        pass
    return {"status": "removed", "path": str(target)}


# ─────────────────────────────────────────────────────────────
# Manually-added NAS (the "Devices" page) — FreeRADIUS client
# registration.
#
# The Setup Wizard v3 auto-provisions a client file per run
# (wizard-run-<id>.conf) so a WG-onboarded router authenticates
# the moment the wizard completes. But a router added through the
# plain "Devices" CRUD page (/admin/radius/devices) has NO such
# file — and until this module existed, nothing on that path ever
# told FreeRADIUS the router's source IP + shared secret. The
# packets arrived at 0.0.0.0:1812 from an UNKNOWN client, so
# FreeRADIUS silently discarded them (RFC 2865 §3: "a request
# from a client for which the RADIUS server has no shared secret
# MUST be silently discarded"). RouterOS then reports «الرديوس لا
# يستجيب» / "RADIUS not responding".
#
# These helpers close that gap by writing ONE file per NAS row:
#
#     /app/instance/freeradius-clients-wizard/nas-<id>.conf
#
# in the SAME managed directory the wizard uses, so the existing
# `$INCLUDE /data/freeradius-clients-wizard/` line and the
# entrypoint reload-trigger watcher pick it up live (~5s) — no
# FreeRADIUS restart, no clients.conf edit, no redeploy.
#
# The filename prefix `nas-` deliberately differs from the
# wizard's `wizard-run-` so the reconciler (which only matches
# `^wizard-run-(\d+)\.conf$`) never treats these as orphans and
# deletes them. The two schemes coexist in one directory.
_NAS_FILE_RE = re.compile(r"^nas-(\d+)\.conf$")


def _touch_reload_trigger(target_dir: Path) -> None:
    """Bump the reload trigger so the freeradius entrypoint
    watcher SIGTERMs freeradius and the supervisor reloads all
    client files. Best-effort — a missed trigger just delays the
    pickup until the next write/reconcile."""
    trigger = target_dir / ".reload-trigger"
    try:
        trigger.touch(exist_ok=True)
        now = time.time()
        os.utime(trigger, (now, now))
    except Exception:  # noqa: BLE001
        _LOG.warning(
            "could not touch reload trigger %s — operator may "
            "need to restart freeradius manually",
            trigger,
            exc_info=True,
        )


def write_client_for_nas(
    *,
    nas_id: int,
    ipaddr: str,
    secret: str,
    shortname: str | None = None,
    require_message_authenticator: bool = False,
) -> dict[str, Any]:
    """Atomically write the FreeRADIUS client block for one
    manually-added NAS row (nas_devices.id). Idempotent: re-running
    with the same inputs overwrites the file in place; the reload
    trigger is bumped every time so drift self-heals.

    `ipaddr` MUST be the address FreeRADIUS actually sees as the
    UDP source of the router's Access-Request — i.e. the router's
    tunnel-side IP (10.10.0.x) for a VPN router, or its reachable
    IP for a direct one. A mismatch here is the classic "secret is
    right but auth still drops" failure.
    """
    if not ipaddr:
        raise FreeRadiusProvisioningError("ipaddr is required")
    if not secret:
        raise FreeRadiusProvisioningError("secret is required")
    if _UNSAFE.search(secret):
        raise FreeRadiusProvisioningError(
            "secret contains characters that break clients.conf "
            "parsing (\", }, or newline)",
        )
    if _UNSAFE.search(str(ipaddr)):
        raise FreeRadiusProvisioningError(
            "ipaddr contains characters that break clients.conf "
            "parsing",
        )

    target_dir = _dir()
    try:
        target_dir.mkdir(parents=True, exist_ok=True)
    except PermissionError as exc:
        raise FreeRadiusProvisioningError(
            f"cannot create {target_dir} — fix host volume "
            f"permissions: {exc}",
        ) from exc

    # ── Collision guard (avoid FreeRADIUS "duplicate client"
    # startup crash) ────────────────────────────────────────────
    # FreeRADIUS refuses two client blocks with the same ipaddr and
    # crash-loops. The Setup Wizard OWNS the VPN range: if a
    # wizard-run-*.conf already registers this ipaddr, do NOT write
    # a competing nas-*.conf — the wizard file already lets this
    # router authenticate. Writing ours would duplicate the ipaddr.
    wiz_owner = _wizard_file_for_ip(target_dir, str(ipaddr).strip())
    if wiz_owner is not None:
        _LOG.info(
            "nas-%s: ipaddr %s already registered by %s (wizard "
            "owns the VPN range) — skipping nas client file",
            nas_id, ipaddr, wiz_owner.name,
        )
        return {
            "status": "skipped_wizard_owns_ip",
            "ipaddr": str(ipaddr),
            "wizard_file": wiz_owner.name,
        }
    # Purge any OTHER nas-*.conf claiming the same ipaddr (stale row
    # replaced, or the operator moved the IP between routers) so we
    # keep the 1-ipaddr → 1-file invariant among nas files too.
    _purge_stale_nas_files_for_ip(
        target_dir, str(ipaddr).strip(), except_nas_id=int(nas_id),
    )

    short = shortname or f"nas-{int(nas_id)}"
    safe_short = re.sub(r"[^A-Za-z0-9_-]+", "-", short)[:48] or f"nas{nas_id}"
    require_ma = "yes" if require_message_authenticator else "no"

    block = (
        f"# AUTO-GENERATED by HobeRadius (Devices page)\n"
        f"# nas_devices.id: {int(nas_id)}\n"
        f"# Generated at: {time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())}\n"
        f"# DO NOT EDIT — regenerated whenever the NAS row is saved.\n"
        f"# Disable/delete the NAS in the panel to revoke access.\n"
        f"\n"
        f"client nas-{int(nas_id)} {{\n"
        f"    ipaddr      = {ipaddr}\n"
        f"    secret      = {secret}\n"
        f"    require_message_authenticator = {require_ma}\n"
        f"    nas_type    = mikrotik\n"
        f"    shortname   = {safe_short}\n"
        f"}}\n"
    )

    target = target_dir / f"nas-{int(nas_id)}.conf"
    resolved = target.resolve()
    if not str(resolved).startswith(str(target_dir.resolve())):
        raise FreeRadiusProvisioningError(
            "refusing to write outside the managed directory",
        )

    tmp = target.with_suffix(".conf.tmp")
    try:
        tmp.write_text(block, encoding="utf-8")
        tmp.replace(target)  # atomic rename
    except PermissionError as exc:
        raise FreeRadiusProvisioningError(
            f"cannot write {target}: {exc}",
        ) from exc

    _touch_reload_trigger(target_dir)

    return {
        "status": "written",
        "path_in_hoberadius": str(target),
        "path_in_freeradius": str(target).replace(
            "/app/instance/", "/data/",
        ),
        "shortname": safe_short,
        "ipaddr": str(ipaddr),
        "expected_reload_seconds": 5,
    }


def remove_client_for_nas(*, nas_id: int) -> dict[str, Any]:
    """Delete the client block for one manually-added NAS. Used
    when the NAS is disabled, archived, or deleted."""
    target_dir = _dir()
    target = target_dir / f"nas-{int(nas_id)}.conf"
    if not target.exists():
        return {"status": "absent", "path": str(target)}
    try:
        target.unlink()
    except Exception as exc:  # noqa: BLE001
        raise FreeRadiusProvisioningError(
            f"cannot remove {target}: {exc}",
        ) from exc
    _touch_reload_trigger(target_dir)
    return {"status": "removed", "path": str(target)}


def _wizard_file_for_ip(target_dir: Path, ipaddr: str):
    """Return the Path of a wizard-run-*.conf that already registers
    `ipaddr`, or None. Used to avoid a duplicate-ipaddr collision
    when a manually-added NAS lands on an IP the wizard owns."""
    if not ipaddr or not target_dir.is_dir():
        return None
    for path in target_dir.iterdir():
        if not path.is_file() or not _RUN_FILE_RE.match(path.name):
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except Exception:  # noqa: BLE001
            continue
        m = _IPADDR_RE.search(text)
        if m and m.group(1).strip() == ipaddr:
            return path
    return None


def _purge_stale_nas_files_for_ip(
    target_dir: Path, ipaddr: str, *, except_nas_id: int,
) -> list[str]:
    """Remove any nas-*.conf with the same `ipaddr` but a different
    nas_id — keeps 1-ipaddr → 1-file among the manual NAS files."""
    removed: list[str] = []
    if not ipaddr or not target_dir.is_dir():
        return removed
    for path in target_dir.iterdir():
        if not path.is_file():
            continue
        m = _NAS_FILE_RE.match(path.name)
        if not m or int(m.group(1)) == int(except_nas_id):
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except Exception:  # noqa: BLE001
            continue
        ip_match = _IPADDR_RE.search(text)
        if not ip_match or ip_match.group(1).strip() != ipaddr:
            continue
        try:
            path.unlink()
            removed.append(str(path))
            _LOG.info(
                "purged stale nas client file for ipaddr %s: %s",
                ipaddr, path.name,
            )
        except Exception:  # noqa: BLE001
            _LOG.warning(
                "could not purge stale %s", path, exc_info=True,
            )
    return removed


_IPADDR_RE = re.compile(r"^\s*ipaddr\s*=\s*(\S+)", re.MULTILINE)
_RUN_FILE_RE = re.compile(r"^wizard-run-(\d+)\.conf$")


def _purge_stale_files_for_ip(
    target_dir: Path, ipaddr: str, *, except_run_id: int,
) -> list[str]:
    """Remove any wizard-run-*.conf in `target_dir` that has
    the same `ipaddr =` value but a different run_id. Returns
    paths of removed files for logging."""
    removed: list[str] = []
    if not target_dir.is_dir():
        return removed
    for path in target_dir.iterdir():
        if not path.is_file():
            continue
        m = _RUN_FILE_RE.match(path.name)
        if not m:
            continue
        if int(m.group(1)) == int(except_run_id):
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except Exception:  # noqa: BLE001
            continue
        ip_match = _IPADDR_RE.search(text)
        if not ip_match:
            continue
        if ip_match.group(1).strip() != str(ipaddr).strip():
            continue
        # Same ipaddr, different run → stale.
        try:
            path.unlink()
            removed.append(str(path))
            _LOG.info(
                "purged stale clients.conf for ipaddr %s: %s",
                ipaddr, path.name,
            )
        except Exception:  # noqa: BLE001
            _LOG.warning(
                "could not purge stale %s", path, exc_info=True,
            )
    return removed


def reconcile_with_state(
    *, tenant_id: int | None = None,
) -> dict[str, Any]:
    """Periodic sweep that reconciles files in the
    clients-wizard directory with the wizard's source-of-truth
    (setup_wizard_runs.state_json).

    CRITICAL: scans active runs across ALL tenants, not just
    one. The clients-wizard directory is GLOBAL to the
    FreeRADIUS instance — a per-tenant sweep would
    incorrectly delete files belonging to other tenants'
    routers, taking them OFFLINE. See postmortem #21.

    The `tenant_id` argument is preserved for compatibility
    with older callers but ignored for the orphan check
    (INV-2). For backward compatibility, when tenant_id is
    provided, INV-1 still only writes files for THAT tenant's
    active runs (avoids one tenant's sweep stomping on another's
    in-flight write). When tenant_id is None, INV-1 covers
    all tenants.

    Invariants enforced:
      INV-1: every active run (v3_state ∈ VERIFYING/REGISTERING/
             COMPLETE) MUST have a matching wizard-run-<id>.conf
             with the right secret. Violations → rewrite.
      INV-2: every wizard-run-<id>.conf MUST correspond to an
             active run *for some tenant*. Orphans → delete.
      INV-3: no two files may share the same ipaddr.
             Duplicates → keep newest run_id.

    Every reconcile action is also written to audit_log at
    severity=warning so production has a forensic trail of
    every drift correction.
    """
    from ..db.connection import db
    import json as _json

    target_dir = _dir()
    actions: dict[str, list[str]] = {
        "rewritten": [], "deleted": [], "deduped": [],
        "ok": [],
    }
    # NOTE: don't early-return when the directory is missing.
    # write_client_for_run() recreates it, and we still need
    # to write files for any active runs found in the DB.

    # ── Index files by run_id ────────────────────────────
    files_by_run: dict[int, Path] = {}
    files_by_ip: dict[str, list[Path]] = {}
    iterable = (
        target_dir.iterdir() if target_dir.is_dir() else []
    )
    for path in iterable:
        if not path.is_file():
            continue
        m = _RUN_FILE_RE.match(path.name)
        if not m:
            continue
        rid = int(m.group(1))
        files_by_run[rid] = path
        try:
            text = path.read_text(encoding="utf-8")
        except Exception:  # noqa: BLE001
            continue
        ip_match = _IPADDR_RE.search(text)
        if ip_match:
            ip = ip_match.group(1).strip()
            files_by_ip.setdefault(ip, []).append(path)

    # ── Index active runs across ALL tenants ────────────
    # This is the key fix from postmortem #21: the
    # clients-wizard dir is a GLOBAL resource, so the orphan
    # check must consider runs from every tenant. Otherwise
    # a per-tenant sweep would delete the other tenant's
    # active client files.
    global_active_runs: dict[int, dict[str, Any]] = {}
    per_tenant_active_runs: dict[int, dict[str, Any]] = {}
    sql = (
        "SELECT id, tenant_id, v3_state, state_json "
        "FROM setup_wizard_runs "
        "WHERE v3_state IN "
        "  ('VERIFYING', 'REGISTERING', 'COMPLETE')"
    )
    params: tuple = ()
    if tenant_id is not None:
        sql_tenant = sql + " AND tenant_id=?"
        params = (int(tenant_id),)
    else:
        sql_tenant = sql
        params = ()

    for r in db().execute(sql).fetchall():
        try:
            state = _json.loads(r["state_json"] or "{}") or {}
        except (TypeError, ValueError):
            state = {}
        if not (state.get("router_vpn_ip")
                and state.get("radius_secret")):
            continue
        rid = int(r["id"])
        state["_tenant_id"] = int(r["tenant_id"])
        global_active_runs[rid] = state
        if (tenant_id is None
                or int(r["tenant_id"]) == int(tenant_id)):
            per_tenant_active_runs[rid] = state

    # ── INV-1: every active run has a correct file ──────
    # Scoped to per-tenant (or all if tenant_id is None) so
    # concurrent reconciles don't race on the same files.
    for rid, state in per_tenant_active_runs.items():
        expected_secret = state["radius_secret"]
        expected_ip = state["router_vpn_ip"]
        path = files_by_run.get(rid)
        needs_write = False
        prev_secret_hash = ""
        if not path or not path.exists():
            needs_write = True
        else:
            try:
                text = path.read_text(encoding="utf-8")
                ok_secret = (
                    f"secret      = {expected_secret}" in text
                )
                ok_ip = (
                    f"ipaddr      = {expected_ip}" in text
                )
                # Capture a hash of the existing secret for
                # the audit row — never log the literal value.
                ex_match = re.search(
                    r"secret\s*=\s*(\S+)", text,
                )
                if ex_match:
                    import hashlib
                    prev_secret_hash = hashlib.sha256(
                        ex_match.group(1).encode(),
                    ).hexdigest()[:12]
                if not (ok_secret and ok_ip):
                    needs_write = True
            except Exception:  # noqa: BLE001
                needs_write = True
        if needs_write:
            try:
                write_client_for_run(
                    run_id=rid,
                    router_vpn_ip=expected_ip,
                    radius_secret=expected_secret,
                )
                actions["rewritten"].append(
                    f"wizard-run-{rid}.conf",
                )
                _audit_reconcile(
                    action="wizard_radius_reconcile_rewrite",
                    tenant_id=state.get("_tenant_id"),
                    run_id=rid,
                    payload={
                        "file": f"wizard-run-{rid}.conf",
                        "router_vpn_ip": expected_ip,
                        "prev_secret_sha256_12": prev_secret_hash,
                        "reason": "missing_or_drifted",
                    },
                )
            except FreeRadiusProvisioningError as exc:
                _LOG.warning(
                    "reconciler: could not write for run %s: %s",
                    rid, exc,
                )
        else:
            actions["ok"].append(f"wizard-run-{rid}.conf")

    # ── INV-2: every file belongs to SOME tenant's active
    # run. global_active_runs covers ALL tenants regardless
    # of the per-tenant scoping above. ─────────────────────
    for rid, path in files_by_run.items():
        if rid in global_active_runs:
            continue
        try:
            # Capture file contents for the audit trail
            # BEFORE deleting — once deleted we can't
            # reconstruct what was there.
            try:
                text_before = path.read_text(encoding="utf-8")
                ip_match = re.search(
                    r"ipaddr\s*=\s*(\S+)", text_before,
                )
                deleted_ip = (
                    ip_match.group(1) if ip_match else ""
                )
            except Exception:  # noqa: BLE001
                deleted_ip = ""
            path.unlink()
            actions["deleted"].append(path.name)
            _LOG.info(
                "reconciler: deleted orphan file %s", path.name,
            )
            _audit_reconcile(
                action="wizard_radius_reconcile_delete_orphan",
                tenant_id=None,
                run_id=rid,
                payload={
                    "file": path.name,
                    "router_vpn_ip": deleted_ip,
                    "reason":
                        "no_active_run_across_any_tenant",
                },
            )
        except Exception:  # noqa: BLE001
            _LOG.warning(
                "reconciler: could not delete orphan %s",
                path, exc_info=True,
            )

    # ── INV-3: deduplicate by ipaddr ─────────────────────
    for ip, paths in files_by_ip.items():
        if len(paths) <= 1:
            continue
        paths_sorted = sorted(
            paths,
            key=lambda p: int(
                _RUN_FILE_RE.match(p.name).group(1),
            ),
            reverse=True,
        )
        keeper = paths_sorted[0]
        for p in paths_sorted[1:]:
            if not p.exists():
                continue
            try:
                p.unlink()
                actions["deduped"].append(p.name)
                _LOG.info(
                    "reconciler: deduped %s (kept %s for %s)",
                    p.name, keeper.name, ip,
                )
                _audit_reconcile(
                    action="wizard_radius_reconcile_dedupe",
                    tenant_id=None,
                    run_id=int(
                        _RUN_FILE_RE.match(p.name).group(1),
                    ),
                    payload={
                        "file": p.name,
                        "kept_file": keeper.name,
                        "shared_ipaddr": ip,
                    },
                )
            except Exception:  # noqa: BLE001
                _LOG.warning(
                    "reconciler: could not dedupe %s",
                    p, exc_info=True,
                )

    # Touch the reload trigger if we changed anything so
    # freeradius picks up the new state within ~5 seconds.
    if (actions["rewritten"] or actions["deleted"]
            or actions["deduped"]):
        trigger = target_dir / ".reload-trigger"
        try:
            trigger.touch(exist_ok=True)
            now = time.time()
            os.utime(trigger, (now, now))
        except Exception:  # noqa: BLE001
            _LOG.warning(
                "reconciler: could not touch reload trigger",
                exc_info=True,
            )

    return {
        **actions,
        "scanned_runs": len(per_tenant_active_runs),
        "scanned_files": len(files_by_run),
        "global_active_runs": len(global_active_runs),
    }


def _audit_reconcile(
    *, action: str,
    tenant_id: int | None,
    run_id: int,
    payload: dict[str, Any],
) -> None:
    """Production audit trail — every reconciler action
    appears in audit_log with severity=warning so support can
    trace exactly what changed when. Never logs literal
    secrets; only short SHA-256 prefixes for forensic
    comparison."""
    try:
        from .audit import RadiusAuditService
        # Audit is tenant-scoped via flask.g.tenant_id but
        # the reconciler runs cross-tenant. Use the run's
        # tenant when known, else fall back to default.
        RadiusAuditService().record(
            actor="setup_wizard_radius_reconciler",
            action=action,
            target_type="wizard_clients_conf",
            target_id=str(run_id),
            payload={**payload, "tenant_id": tenant_id},
            severity="warning",
            result_status="reconciled",
        )
    except Exception:  # noqa: BLE001
        _LOG.warning(
            "reconciler audit write failed for %s run=%s",
            action, run_id, exc_info=True,
        )


def reconcile_nas_client_files(
    *, tenant_id: int | None = None,
) -> dict[str, Any]:
    """Self-healing sweep for the MANUAL "Devices" path
    (nas-<id>.conf), complementing reconcile_with_state() which
    owns the wizard files (wizard-run-<id>.conf).

    Why this exists: freeradius_translator.sync_nas writes a
    client file only when a NAS row is saved/deleted through the
    adapter. A router whose row already exists (e.g. created
    before this feature, restored from a backup, or whose file was
    manually removed) would have NO client file and FreeRADIUS
    would silently discard its packets (RFC 2865) → «الرديوس لا
    يستجيب» with NOTHING in the login-attempts log. This sweep
    guarantees every enabled nas_devices row has a correct file
    and every orphan nas-*.conf is removed — within one interval.

    Invariants (mirror of reconcile_with_state, scoped to nas-*):
      N1: every enabled, non-deleted nas_devices row has a
          nas-<id>.conf with the right ipaddr + secret (unless a
          wizard file already owns that ipaddr — then it's
          intentionally skipped to avoid a duplicate-client crash).
      N2: every nas-<id>.conf maps to an enabled, non-deleted
          nas_devices row (across ALL tenants — the directory is a
          global FreeRADIUS resource). Orphans → delete.

    Idempotent: writes/removes only on drift, and touches the
    reload trigger only when something actually changed (no reload
    storm)."""
    from ..db.connection import db

    target_dir = _dir()
    actions: dict[str, list[str]] = {
        "rewritten": [], "deleted": [], "ok": [],
    }

    # ── Index existing nas-*.conf by nas_id ───────────────────
    files_by_nas: dict[int, Path] = {}
    if target_dir.is_dir():
        for path in target_dir.iterdir():
            if not path.is_file():
                continue
            m = _NAS_FILE_RE.match(path.name)
            if m:
                files_by_nas[int(m.group(1))] = path

    # ── Index enabled routers across ALL tenants ──────────────
    # The clients dir is global, so N2's orphan check must see
    # every tenant's enabled routers (same rationale as
    # reconcile_with_state / postmortem #21).
    enabled_ids: set[int] = set()
    rows = db().execute(
        "SELECT id, tenant_id, address, secret, "
        "       COALESCE(management_remote_address, '') AS mra, "
        "       COALESCE(vpn_peer_address, '') AS vpn_peer_address, "
        "       COALESCE(shortname, '') AS shortname, "
        "       COALESCE(name, '') AS name, "
        "       COALESCE(require_message_authenticator, 0) AS require_ma "
        "FROM nas_devices "
        "WHERE enabled = 1 AND (deleted_at IS NULL OR deleted_at = '')"
    ).fetchall()

    changed = False
    for r in rows:
        nas_id = int(r["id"])
        # Tunnel IP first (SSTP mgmt_remote → WG vpn_peer → direct
        # address) — the source IP FreeRADIUS actually sees.
        source_ip = (
            str(r["mra"] or "").strip()
            or str(r["vpn_peer_address"] or "").strip()
            or str(r["address"] or "").strip()
        )
        secret = str(r["secret"] or "").strip()
        if not source_ip or not secret:
            # Nothing we can register (incomplete row) — leave it.
            continue
        enabled_ids.add(nas_id)

        # Drift check: only write when missing or content differs,
        # so we never touch the reload trigger needlessly.
        path = files_by_nas.get(nas_id)
        needs_write = True
        if path is not None and path.exists():
            try:
                text = path.read_text(encoding="utf-8")
                if (f"ipaddr      = {source_ip}" in text
                        and f"secret      = {secret}" in text):
                    needs_write = False
            except Exception:  # noqa: BLE001
                needs_write = True
        if not needs_write:
            actions["ok"].append(f"nas-{nas_id}.conf")
            continue
        try:
            res = write_client_for_nas(
                nas_id=nas_id,
                ipaddr=source_ip,
                secret=secret,
                shortname=(str(r["shortname"] or "").strip()
                           or str(r["name"] or "").strip()),
                require_message_authenticator=bool(r["require_ma"]),
            )
            # A wizard file already owning the IP is a no-op skip,
            # not a change.
            if res.get("status") == "written":
                actions["rewritten"].append(f"nas-{nas_id}.conf")
                changed = True
        except FreeRadiusProvisioningError as exc:
            _LOG.warning(
                "reconcile_nas: could not write nas-%s.conf: %s",
                nas_id, exc,
            )

    # ── N2: delete orphan nas-*.conf (no enabled row) ─────────
    for nas_id, path in files_by_nas.items():
        if nas_id in enabled_ids:
            continue
        try:
            path.unlink()
            actions["deleted"].append(path.name)
            changed = True
            _LOG.info(
                "reconcile_nas: deleted orphan file %s "
                "(no enabled nas_devices row)", path.name,
            )
        except Exception:  # noqa: BLE001
            _LOG.warning(
                "reconcile_nas: could not delete orphan %s",
                path, exc_info=True,
            )

    if changed:
        _touch_reload_trigger(target_dir)

    return {
        **actions,
        "scanned_rows": len(rows),
        "scanned_files": len(files_by_nas),
    }


__all__ = [
    "write_client_for_run",
    "remove_client_for_run",
    "write_client_for_nas",
    "remove_client_for_nas",
    "reconcile_with_state",
    "reconcile_nas_client_files",
    "FreeRadiusProvisioningError",
]
