"""SW-server-side — write FreeRADIUS clients.conf snippet from
the wizard, no SSH required.

After Step 3 the operator has a router talking to 10.10.0.1
with a fresh shared secret. But FreeRADIUS rejects the auth
because clients.conf on the server doesn't know that router.

This service automates the missing piece. Per wizard-run it
writes ONE file:

    /app/instance/freeradius-clients-wizard/wizard-run-<id>.conf

which freeradius sees via the shared `instance/` volume as
`/data/freeradius-clients-wizard/wizard-run-<id>.conf`. The
main `clients.conf` includes that directory:

    $INCLUDE /data/freeradius-clients-wizard/*.conf

After writing, this service touches `.reload-trigger` in the
same directory. The freeradius entrypoint's background
watcher picks that up and SIGTERMs the freeradius process —
the supervisor loop relaunches it and the new client is
loaded. Total reload time: ~5 seconds.

Files in this directory are owned by hoberadius (uid 999) and
group=freerad (gid 101) thanks to the setgid bit the
entrypoint sets on `/data`. Both processes can read+write.

Filename convention pins the file to a specific run, so:
* re-running the wizard on the same run overwrites the file
* retire/abandon flows can remove the file cleanly
* the emergency fleet reset wipes everything matching
  `wizard-run-*.conf`

Safety: refuses to write outside the managed directory.
Refuses to use a secret containing characters that would
break the clients.conf syntax (literal `"` or `}`).
"""
from __future__ import annotations

import logging
import os
import re
import time
from pathlib import Path
from typing import Any


_LOG = logging.getLogger(__name__)


# Default location inside the hoberadius container. The host
# directory `/opt/hoberadius/instance/freeradius-clients-wizard/`
# is bind-mounted to both containers:
#   hoberadius: /app/instance/freeradius-clients-wizard
#   freeradius: /data/freeradius-clients-wizard
_DEFAULT_DIR = Path("/app/instance/freeradius-clients-wizard")
_DIR_ENV = "HOBERADIUS_FREERADIUS_CLIENTS_WIZARD_DIR"


# Sanity-check on the secret + shortname. clients.conf is
# parsed as RouterOS-style key=value blocks — any unescaped
# `"`, `}`, or newline breaks the parser silently.
_UNSAFE = re.compile(r'[\"\}\n\r]')


class FreeRadiusProvisioningError(Exception):
    """Raised when the snippet can't be written safely."""


def _dir() -> Path:
    raw = os.environ.get(_DIR_ENV)
    return Path(raw) if raw else _DEFAULT_DIR


def write_client_for_run(
    *,
    run_id: int,
    router_vpn_ip: str,
    radius_secret: str,
    shortname: str | None = None,
) -> dict[str, Any]:
    """Atomically write the client block for one wizard run.
    Returns a small summary suitable for logging and UI.

    Side effect: removes any existing `wizard-run-*.conf`
    that targets the SAME `router_vpn_ip` but belongs to a
    different run_id. This enforces the invariant
    'one ipaddr → one active client file'. Without this,
    re-running the wizard for the same router (or replacing
    one router with another using the same VPN slot) would
    leave stale entries that may carry an obsolete secret.
    """
    if not router_vpn_ip:
        raise FreeRadiusProvisioningError(
            "router_vpn_ip is required",
        )
    if not radius_secret:
        raise FreeRadiusProvisioningError(
            "radius_secret is required",
        )
    if _UNSAFE.search(radius_secret):
        raise FreeRadiusProvisioningError(
            "radius_secret contains characters that break "
            "clients.conf parsing (\", }, or newline)",
        )

    target_dir = _dir()
    try:
        target_dir.mkdir(parents=True, exist_ok=True)
    except PermissionError as exc:
        raise FreeRadiusProvisioningError(
            f"cannot create {target_dir} — fix host volume "
            f"permissions: {exc}",
        ) from exc

    # Enforce 1-ip → 1-file. Wipe any stale file for this IP
    # that belongs to a different run BEFORE writing the new
    # one (so two runs for the same router can't both have
    # files claiming the same client IP).
    _purge_stale_files_for_ip(
        target_dir, router_vpn_ip, except_run_id=run_id,
    )

    short = shortname or f"wizard-router-{int(run_id)}"
    # FreeRADIUS shortnames + client-block names must be safe
    # identifiers — strip anything weird.
    safe_short = re.sub(r"[^A-Za-z0-9_-]+", "-", short)[:48] or f"r{run_id}"

    block = (
        f"# AUTO-GENERATED by HobeRadius Setup Wizard v3\n"
        f"# Wizard run: {int(run_id)}\n"
        f"# Generated at: {time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())}\n"
        f"# DO NOT EDIT — the wizard will overwrite on re-run.\n"
        f"# Remove this file to revoke the router's RADIUS access.\n"
        f"\n"
        f"client router-{int(run_id)} {{\n"
        f"    ipaddr      = {router_vpn_ip}\n"
        f"    secret      = {radius_secret}\n"
        f"    require_message_authenticator = no\n"
        f"    nas_type    = mikrotik\n"
        f"    shortname   = {safe_short}\n"
        f"}}\n"
    )

    target = target_dir / f"wizard-run-{int(run_id)}.conf"
    # Resolve and double-check we're still under the managed
    # directory — defends against any future bug where a
    # tainted run_id could escape.
    resolved = target.resolve()
    if not str(resolved).startswith(str(target_dir.resolve())):
        raise FreeRadiusProvisioningError(
            "refusing to write outside the managed directory",
        )

    tmp = target.with_suffix(".conf.tmp")
    try:
        tmp.write_text(block, encoding="utf-8")
        tmp.replace(target)  # atomic rename
    except PermissionError as exc:
        raise FreeRadiusProvisioningError(
            f"cannot write {target}: {exc}",
        ) from exc

    # Touch the reload trigger so the freeradius entrypoint's
    # watcher picks up the change. Idempotent — repeat writes
    # just bump the mtime.
    trigger = target_dir / ".reload-trigger"
    try:
        trigger.touch(exist_ok=True)
        # Bump mtime explicitly even if file existed.
        now = time.time()
        os.utime(trigger, (now, now))
    except Exception:  # noqa: BLE001
        _LOG.warning(
            "could not touch reload trigger %s — operator may "
            "need to restart freeradius manually",
            trigger,
            exc_info=True,
        )

    return {
        "status": "written",
        "path_in_hoberadius": str(target),
        "path_in_freeradius": str(target).replace(
            "/app/instance/", "/data/",
        ),
        "shortname": safe_short,
        "reload_trigger": str(trigger),
        "expected_reload_seconds": 5,
    }


def remove_client_for_run(
    *, run_id: int,
) -> dict[str, Any]:
    """Delete the client block for one wizard run. Used by the
    retire/abandon/emergency-reset flows."""
    target = _dir() / f"wizard-run-{int(run_id)}.conf"
    if not target.exists():
        return {"status": "absent", "path": str(target)}
    try:
        target.unlink()
    except Exception as exc:  # noqa: BLE001
        raise FreeRadiusProvisioningError(
            f"cannot remove {target}: {exc}",
        ) from exc
    # Trigger reload to drop the revoked client.
    trigger = _dir() / ".reload-trigger"
    try:
        trigger.touch(exist_ok=True)
        now = time.time()
        os.utime(trigger, (now, now))
    except Exception:  # noqa: BLE001
        pass
    return {"status": "removed", "path": str(target)}


_IPADDR_RE = re.compile(r"^\s*ipaddr\s*=\s*(\S+)", re.MULTILINE)
_RUN_FILE_RE = re.compile(r"^wizard-run-(\d+)\.conf$")


def _purge_stale_files_for_ip(
    target_dir: Path, ipaddr: str, *, except_run_id: int,
) -> list[str]:
    """Remove any wizard-run-*.conf in `target_dir` that has
    the same `ipaddr =` value but a different run_id. Returns
    paths of removed files for logging."""
    removed: list[str] = []
    if not target_dir.is_dir():
        return removed
    for path in target_dir.iterdir():
        if not path.is_file():
            continue
        m = _RUN_FILE_RE.match(path.name)
        if not m:
            continue
        if int(m.group(1)) == int(except_run_id):
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except Exception:  # noqa: BLE001
            continue
        ip_match = _IPADDR_RE.search(text)
        if not ip_match:
            continue
        if ip_match.group(1).strip() != str(ipaddr).strip():
            continue
        # Same ipaddr, different run → stale.
        try:
            path.unlink()
            removed.append(str(path))
            _LOG.info(
                "purged stale clients.conf for ipaddr %s: %s",
                ipaddr, path.name,
            )
        except Exception:  # noqa: BLE001
            _LOG.warning(
                "could not purge stale %s", path, exc_info=True,
            )
    return removed


def reconcile_with_state(
    *, tenant_id: int = 1,
) -> dict[str, Any]:
    """Periodic sweep that reconciles files in the clients-
    wizard directory with the wizard's source-of-truth
    (setup_wizard_runs.state_json).

    Invariants enforced:
      INV-1: every active run (v3_state in
             VERIFYING/REGISTERING/COMPLETE) MUST have a
             matching wizard-run-<id>.conf whose `secret`
             field equals state_json.radius_secret.
      INV-2: every wizard-run-<id>.conf MUST correspond to
             an active run with matching state.
      INV-3: no two files may share the same ipaddr.

    For each violation:
      INV-1 mismatch → re-write the file from state_json.
      INV-2 orphan   → remove the file.
      INV-3 duplicate → keep the most recent run's file.

    Returns a structured summary suitable for the worker's
    audit log.
    """
    from ..db.connection import db
    import json as _json

    target_dir = _dir()
    actions: dict[str, list[str]] = {
        "rewritten": [], "deleted": [], "deduped": [],
        "ok": [],
    }
    # NOTE: don't early-return when the directory is missing.
    # write_client_for_run() recreates it, and we still need
    # to write files for any active runs found in the DB.
    # The file-scan loop below tolerates a non-existent dir.

    # ── Index files by run_id ────────────────────────────
    files_by_run: dict[int, Path] = {}
    files_by_ip: dict[str, list[Path]] = {}
    iterable = target_dir.iterdir() if target_dir.is_dir() else []
    for path in iterable:
        if not path.is_file():
            continue
        m = _RUN_FILE_RE.match(path.name)
        if not m:
            continue
        rid = int(m.group(1))
        files_by_run[rid] = path
        try:
            text = path.read_text(encoding="utf-8")
        except Exception:  # noqa: BLE001
            continue
        ip_match = _IPADDR_RE.search(text)
        if ip_match:
            ip = ip_match.group(1).strip()
            files_by_ip.setdefault(ip, []).append(path)

    # ── Index active runs from DB ────────────────────────
    rows = db().execute(
        """SELECT id, v3_state, state_json
           FROM setup_wizard_runs
           WHERE tenant_id=?
             AND v3_state IN
                 ('VERIFYING', 'REGISTERING', 'COMPLETE')""",
        (int(tenant_id),),
    ).fetchall()
    active_runs: dict[int, dict[str, Any]] = {}
    for r in rows:
        try:
            state = _json.loads(r["state_json"] or "{}") or {}
        except (TypeError, ValueError):
            state = {}
        if state.get("router_vpn_ip") and state.get("radius_secret"):
            active_runs[int(r["id"])] = state

    # ── INV-1: every active run has a correct file ──────
    for rid, state in active_runs.items():
        expected_secret = state["radius_secret"]
        expected_ip = state["router_vpn_ip"]
        path = files_by_run.get(rid)
        needs_write = False
        if not path or not path.exists():
            needs_write = True
        else:
            try:
                text = path.read_text(encoding="utf-8")
                ok_secret = (
                    f"secret      = {expected_secret}" in text
                )
                ok_ip = (
                    f"ipaddr      = {expected_ip}" in text
                )
                if not (ok_secret and ok_ip):
                    needs_write = True
            except Exception:  # noqa: BLE001
                needs_write = True
        if needs_write:
            try:
                write_client_for_run(
                    run_id=rid,
                    router_vpn_ip=expected_ip,
                    radius_secret=expected_secret,
                )
                actions["rewritten"].append(
                    f"wizard-run-{rid}.conf",
                )
            except FreeRadiusProvisioningError as exc:
                _LOG.warning(
                    "reconciler: could not write for run %s: %s",
                    rid, exc,
                )
        else:
            actions["ok"].append(f"wizard-run-{rid}.conf")

    # ── INV-2: every file belongs to an active run ──────
    for rid, path in files_by_run.items():
        if rid in active_runs:
            continue
        try:
            path.unlink()
            actions["deleted"].append(path.name)
            _LOG.info(
                "reconciler: deleted orphan file %s", path.name,
            )
        except Exception:  # noqa: BLE001
            _LOG.warning(
                "reconciler: could not delete orphan %s",
                path, exc_info=True,
            )

    # ── INV-3: deduplicate by ipaddr ─────────────────────
    for ip, paths in files_by_ip.items():
        if len(paths) <= 1:
            continue
        # Keep the file owned by the HIGHEST run_id (newest).
        paths_sorted = sorted(
            paths,
            key=lambda p: int(_RUN_FILE_RE.match(p.name).group(1)),
            reverse=True,
        )
        keeper = paths_sorted[0]
        for p in paths_sorted[1:]:
            if not p.exists():
                continue
            try:
                p.unlink()
                actions["deduped"].append(p.name)
                _LOG.info(
                    "reconciler: deduped %s (kept %s for %s)",
                    p.name, keeper.name, ip,
                )
            except Exception:  # noqa: BLE001
                _LOG.warning(
                    "reconciler: could not dedupe %s",
                    p, exc_info=True,
                )

    # Touch the reload trigger if we changed anything so
    # freeradius picks up the new state within ~5 seconds.
    if (actions["rewritten"] or actions["deleted"]
            or actions["deduped"]):
        trigger = target_dir / ".reload-trigger"
        try:
            trigger.touch(exist_ok=True)
            now = time.time()
            os.utime(trigger, (now, now))
        except Exception:  # noqa: BLE001
            _LOG.warning(
                "reconciler: could not touch reload trigger",
                exc_info=True,
            )

    return {
        **actions,
        "scanned_runs": len(active_runs),
        "scanned_files": len(files_by_run),
    }


__all__ = [
    "write_client_for_run",
    "remove_client_for_run",
    "reconcile_with_state",
    "FreeRadiusProvisioningError",
]
