"""SW-server-side — write FreeRADIUS clients.conf snippet from
the wizard, no SSH required.

After Step 3 the operator has a router talking to 10.10.0.1
with a fresh shared secret. But FreeRADIUS rejects the auth
because clients.conf on the server doesn't know that router.

This service automates the missing piece. Per wizard-run it
writes ONE file:

    /app/instance/freeradius-clients-wizard/wizard-run-<id>.conf

which freeradius sees via the shared `instance/` volume as
`/data/freeradius-clients-wizard/wizard-run-<id>.conf`. The
main `clients.conf` includes that directory:

    $INCLUDE /data/freeradius-clients-wizard/*.conf

After writing, this service touches `.reload-trigger` in the
same directory. The freeradius entrypoint's background
watcher picks that up and SIGTERMs the freeradius process —
the supervisor loop relaunches it and the new client is
loaded. Total reload time: ~5 seconds.

Files in this directory are owned by hoberadius (uid 999) and
group=freerad (gid 101) thanks to the setgid bit the
entrypoint sets on `/data`. Both processes can read+write.

Filename convention pins the file to a specific run, so:
* re-running the wizard on the same run overwrites the file
* retire/abandon flows can remove the file cleanly
* the emergency fleet reset wipes everything matching
  `wizard-run-*.conf`

Safety: refuses to write outside the managed directory.
Refuses to use a secret containing characters that would
break the clients.conf syntax (literal `"` or `}`).
"""
from __future__ import annotations

import logging
import os
import re
import time
from pathlib import Path
from typing import Any


_LOG = logging.getLogger(__name__)


# Default location inside the hoberadius container. The host
# directory `/opt/hoberadius/instance/freeradius-clients-wizard/`
# is bind-mounted to both containers:
#   hoberadius: /app/instance/freeradius-clients-wizard
#   freeradius: /data/freeradius-clients-wizard
_DEFAULT_DIR = Path("/app/instance/freeradius-clients-wizard")
_DIR_ENV = "HOBERADIUS_FREERADIUS_CLIENTS_WIZARD_DIR"


# Sanity-check on the secret + shortname. clients.conf is
# parsed as RouterOS-style key=value blocks — any unescaped
# `"`, `}`, or newline breaks the parser silently.
_UNSAFE = re.compile(r'[\"\}\n\r]')


class FreeRadiusProvisioningError(Exception):
    """Raised when the snippet can't be written safely."""


def _dir() -> Path:
    raw = os.environ.get(_DIR_ENV)
    return Path(raw) if raw else _DEFAULT_DIR


def write_client_for_run(
    *,
    run_id: int,
    router_vpn_ip: str,
    radius_secret: str,
    shortname: str | None = None,
) -> dict[str, Any]:
    """Atomically write the client block for one wizard run.
    Returns a small summary suitable for logging and UI."""
    if not router_vpn_ip:
        raise FreeRadiusProvisioningError(
            "router_vpn_ip is required",
        )
    if not radius_secret:
        raise FreeRadiusProvisioningError(
            "radius_secret is required",
        )
    if _UNSAFE.search(radius_secret):
        raise FreeRadiusProvisioningError(
            "radius_secret contains characters that break "
            "clients.conf parsing (\", }, or newline)",
        )

    target_dir = _dir()
    try:
        target_dir.mkdir(parents=True, exist_ok=True)
    except PermissionError as exc:
        raise FreeRadiusProvisioningError(
            f"cannot create {target_dir} — fix host volume "
            f"permissions: {exc}",
        ) from exc

    short = shortname or f"wizard-router-{int(run_id)}"
    # FreeRADIUS shortnames + client-block names must be safe
    # identifiers — strip anything weird.
    safe_short = re.sub(r"[^A-Za-z0-9_-]+", "-", short)[:48] or f"r{run_id}"

    block = (
        f"# AUTO-GENERATED by HobeRadius Setup Wizard v3\n"
        f"# Wizard run: {int(run_id)}\n"
        f"# Generated at: {time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())}\n"
        f"# DO NOT EDIT — the wizard will overwrite on re-run.\n"
        f"# Remove this file to revoke the router's RADIUS access.\n"
        f"\n"
        f"client router-{int(run_id)} {{\n"
        f"    ipaddr      = {router_vpn_ip}\n"
        f"    secret      = {radius_secret}\n"
        f"    require_message_authenticator = no\n"
        f"    nas_type    = mikrotik\n"
        f"    shortname   = {safe_short}\n"
        f"}}\n"
    )

    target = target_dir / f"wizard-run-{int(run_id)}.conf"
    # Resolve and double-check we're still under the managed
    # directory — defends against any future bug where a
    # tainted run_id could escape.
    resolved = target.resolve()
    if not str(resolved).startswith(str(target_dir.resolve())):
        raise FreeRadiusProvisioningError(
            "refusing to write outside the managed directory",
        )

    tmp = target.with_suffix(".conf.tmp")
    try:
        tmp.write_text(block, encoding="utf-8")
        tmp.replace(target)  # atomic rename
    except PermissionError as exc:
        raise FreeRadiusProvisioningError(
            f"cannot write {target}: {exc}",
        ) from exc

    # Touch the reload trigger so the freeradius entrypoint's
    # watcher picks up the change. Idempotent — repeat writes
    # just bump the mtime.
    trigger = target_dir / ".reload-trigger"
    try:
        trigger.touch(exist_ok=True)
        # Bump mtime explicitly even if file existed.
        now = time.time()
        os.utime(trigger, (now, now))
    except Exception:  # noqa: BLE001
        _LOG.warning(
            "could not touch reload trigger %s — operator may "
            "need to restart freeradius manually",
            trigger,
            exc_info=True,
        )

    return {
        "status": "written",
        "path_in_hoberadius": str(target),
        "path_in_freeradius": str(target).replace(
            "/app/instance/", "/data/",
        ),
        "shortname": safe_short,
        "reload_trigger": str(trigger),
        "expected_reload_seconds": 5,
    }


def remove_client_for_run(
    *, run_id: int,
) -> dict[str, Any]:
    """Delete the client block for one wizard run. Used by the
    retire/abandon/emergency-reset flows."""
    target = _dir() / f"wizard-run-{int(run_id)}.conf"
    if not target.exists():
        return {"status": "absent", "path": str(target)}
    try:
        target.unlink()
    except Exception as exc:  # noqa: BLE001
        raise FreeRadiusProvisioningError(
            f"cannot remove {target}: {exc}",
        ) from exc
    # Trigger reload to drop the revoked client.
    trigger = _dir() / ".reload-trigger"
    try:
        trigger.touch(exist_ok=True)
        now = time.time()
        os.utime(trigger, (now, now))
    except Exception:  # noqa: BLE001
        pass
    return {"status": "removed", "path": str(target)}


__all__ = [
    "write_client_for_run",
    "remove_client_for_run",
    "FreeRadiusProvisioningError",
]
