#!/bin/sh
# ─────────────────────────────────────────────────────────────────────────────
# entrypoint — يحضّر الـ config والـ permissions قبل تشغيل freeradius.
#
# 1) يستبدل placeholder السرّ في mods-enabled/rest (سياق R1: rlm_rest
#    في FR 3.2.x لا يدعم custom HTTP headers ولا env xlat داخل update
#    blocks، فنُمرّر السرّ كـ `_internal_secret` في JSON body).
# 2) يُسوّي ملكية /data كي يستطيع freerad الكتابة على SQLite المشترك
#    بين Flask (uid 999) و FreeRADIUS (freerad).
# ─────────────────────────────────────────────────────────────────────────────
set -e

# ─── 1) secret substitution ──────────────────────────────────────────────────
SECRET="${HOBERADIUS_INTERNAL_SECRET:-}"

if [ -z "$SECRET" ]; then
    echo "[entrypoint] WARN: HOBERADIUS_INTERNAL_SECRET فارغ — Flask سيرفض الطلبات بـ 401." >&2
fi

case "$SECRET" in
    *\"*|*\\*)
        echo "[entrypoint] ERROR: السرّ يحوي \" أو \\ — هذا يكسر JSON body." \
             "استعمل سرّ بسيط (مثل: openssl rand -hex 32)." >&2
        ;;
esac

sed -i "s#__HR_INTERNAL_SECRET__#${SECRET}#g" \
    /etc/freeradius/mods-enabled/rest

if grep -q "__HR_INTERNAL_SECRET__" /etc/freeradius/mods-enabled/rest; then
    echo "[entrypoint] ERROR: __HR_INTERNAL_SECRET__ لم يُستبدَل — تحقّق من env." >&2
fi

# ─── 2) SQLite shared-write ownership normalization ──────────────────────────
# الـ SQLite DB يُملَك من Flask (uid 999) في حجمه الافتراضي على VPS. لكي
# يستطيع freerad (gid=101 في image الـ FR) الكتابة لـ radacct ـ نُضيف
# Group access (read+write) دون تغيير الـ owner ودون chmod 777.
#
# يعمل كـ root هنا (Dockerfile لا يحدّد USER قبل ENTRYPOINT). الـ
# freeradius daemon لاحقاً يَدرُب لـ freerad/freerad حسب radiusd.conf.
#
# الـ |true في النهاية: لا نُسقط الـ container لو فشلت أي عملية. الفحص
# النهائي بـ smoke-test هو المرجع.
if [ -d /data ]; then
    FREERAD_GID="$(getent group freerad 2>/dev/null | cut -d: -f3)"
    : "${FREERAD_GID:=101}"

    # /data نفسه: group=freerad + g+rwX + setgid لكي الـ files الجديدة
    # تأخذ نفس الـ group تلقائياً.
    chgrp "$FREERAD_GID" /data 2>/dev/null || true
    chmod g+rwX /data 2>/dev/null || true
    chmod g+s   /data 2>/dev/null || true

    # ملفّات SQLite (db + WAL/SHM/journal): group=freerad + g+rw
    for f in /data/hoberadius.db /data/hoberadius.db-wal /data/hoberadius.db-shm /data/hoberadius.db-journal; do
        if [ -e "$f" ]; then
            chgrp "$FREERAD_GID" "$f" 2>/dev/null || true
            chmod g+rw           "$f" 2>/dev/null || true
        fi
    done

    # Smoke test: هل يستطيع freerad فعلاً الكتابة في /data؟
    # نُعطي مخرَجَين واضحَين في logs الـ container كي يلاحظهما المُشغّل.
    if su -s /bin/sh freerad -c 'touch /data/.fr_write_check && rm /data/.fr_write_check' 2>/dev/null; then
        echo "[entrypoint] /data write check OK for freerad" >&2
    else
        echo "[entrypoint] WARN: freerad لا يستطيع الكتابة في /data —" \
             "accounting SQL writes ستفشل (لكن Accounting-Response يبقى" \
             "يُرسَل بفضل R1). راجع ownership على المضيف." >&2
    fi
else
    echo "[entrypoint] WARN: /data غير موجود — لن تعمل accounting SQL writes." >&2
fi

# ─── 3) Setup Wizard v3 — auto-provisioned clients dir ──────────────────────
# /data/freeradius-clients-wizard/ holds one .conf per wizard router run.
# Hoberadius (uid 999, gid 999) writes to it via /app/instance/...; freeradius
# reads via /data/...
WIZARD_DIR=/data/freeradius-clients-wizard
if [ ! -d "$WIZARD_DIR" ]; then
    mkdir -p "$WIZARD_DIR"
    chgrp "${FREERAD_GID:-101}" "$WIZARD_DIR" 2>/dev/null || true
    # setgid + g+rwX so files created by hoberadius inherit freerad group
    chmod g+rwxs "$WIZARD_DIR" 2>/dev/null || true
    # World-read so the include glob always picks up new files
    chmod o+rX "$WIZARD_DIR" 2>/dev/null || true
fi

# CRITICAL: FreeRADIUS 3.x's `$INCLUDE <dir>/*.conf` fails to start the
# daemon when the glob matches zero files. The first time the system boots
# (or any time the directory gets emptied by an operator), this would put
# FreeRADIUS into a crash loop that the supervisor below masks. A
# placeholder file ensures the glob always matches at least one entry —
# the file contains only comments so it has no functional effect.
PLACEHOLDER="$WIZARD_DIR/_placeholder.conf"
if [ ! -f "$PLACEHOLDER" ]; then
    cat > "$PLACEHOLDER" <<'EOF'
# AUTO-GENERATED by FreeRADIUS entrypoint — do not remove.
#
# FreeRADIUS 3.x's $INCLUDE wildcard directive fails when the glob
# matches no files. This file exists solely to keep the
# *.conf glob in clients.conf non-empty so the daemon can start
# even before the Setup Wizard has provisioned its first router.
#
# Removing this file will put FreeRADIUS into a crash loop. If you
# need to clean the directory, leave this file in place.
EOF
    chgrp "${FREERAD_GID:-101}" "$PLACEHOLDER" 2>/dev/null || true
    chmod g+r "$PLACEHOLDER" 2>/dev/null || true
fi

# ─── 4) Reload watcher + supervisor loop ─────────────────────────────────────
# Background watcher: polls the .reload-trigger marker every 5 seconds.
# When it changes, kills freeradius — the supervisor loop below relaunches it
# with the new clients.conf snippets loaded.
RELOAD_MARKER="$WIZARD_DIR/.reload-trigger"
LAST_RELOAD_FILE=/tmp/freeradius-last-reload

(
    while sleep 5; do
        [ -f "$RELOAD_MARKER" ] || continue
        TRIGGER_MTIME=$(stat -c %Y "$RELOAD_MARKER" 2>/dev/null || echo 0)
        LAST_MTIME=$(cat "$LAST_RELOAD_FILE" 2>/dev/null || echo 0)
        if [ "$TRIGGER_MTIME" != "$LAST_MTIME" ]; then
            echo "[entrypoint] reload trigger detected (mtime=$TRIGGER_MTIME), restarting freeradius" >&2
            echo "$TRIGGER_MTIME" > "$LAST_RELOAD_FILE"
            # Kill freeradius — supervisor loop below restarts it.
            pkill -TERM freeradius || pkill -TERM radiusd || true
        fi
    done
) &

# Supervisor loop: relaunch freeradius if it exits. Without this, killing
# freeradius to apply new clients.conf would also stop the container (since
# freeradius is the foreground process). The trap forwards SIGTERM from
# `docker stop` so the container exits cleanly when actually requested.
trap 'echo "[entrypoint] received SIGTERM, shutting down" >&2; kill "${FR_PID:-0}" 2>/dev/null; exit 0' TERM INT

while true; do
    freeradius -f -l stdout $FREERADIUS_DEBUG_LEVEL &
    FR_PID=$!
    wait "$FR_PID" || true
    EXIT_CODE=$?
    echo "[entrypoint] freeradius exited with code $EXIT_CODE, restarting in 1s" >&2
    sleep 1
done
